# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_Pro.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(653, 662)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 633, 511))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setStyleSheet(_fromUtf8("QGroupBox {\n"
"  border: 2px solid;\n"
"  border-color: rgba(255, 255, 255, 0);\n"
"}"))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupbox1 = QtGui.QGroupBox(self.groupBox_3)
        self.groupbox1.setAutoFillBackground(False)
        self.groupbox1.setStyleSheet(_fromUtf8("QGroupBox {\n"
"  border: 2px solid;\n"
"  border-color: rgba(255, 255, 255, 0);\n"
"}"))
        self.groupbox1.setTitle(_fromUtf8(""))
        self.groupbox1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupbox1.setObjectName(_fromUtf8("groupbox1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupbox1)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.valve1 = QtGui.QPushButton(self.groupbox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valve1.sizePolicy().hasHeightForWidth())
        self.valve1.setSizePolicy(sizePolicy)
        self.valve1.setCheckable(True)
        self.valve1.setObjectName(_fromUtf8("valve1"))
        self.horizontalLayout_3.addWidget(self.valve1)
        self.line_2 = QtGui.QFrame(self.groupbox1)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_3.addWidget(self.line_2)
        self.edit1_delayh = QtGui.QLineEdit(self.groupbox1)
        self.edit1_delayh.setEnabled(False)
        self.edit1_delayh.setStyleSheet(_fromUtf8(""))
        self.edit1_delayh.setObjectName(_fromUtf8("edit1_delayh"))
        self.horizontalLayout_3.addWidget(self.edit1_delayh)
        self.edit1_delaym = QtGui.QLineEdit(self.groupbox1)
        self.edit1_delaym.setEnabled(False)
        self.edit1_delaym.setObjectName(_fromUtf8("edit1_delaym"))
        self.horizontalLayout_3.addWidget(self.edit1_delaym)
        self.edit1_delays = QtGui.QLineEdit(self.groupbox1)
        self.edit1_delays.setEnabled(False)
        self.edit1_delays.setObjectName(_fromUtf8("edit1_delays"))
        self.horizontalLayout_3.addWidget(self.edit1_delays)
        self.line = QtGui.QFrame(self.groupbox1)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_3.addWidget(self.line)
        self.edit1_onh = QtGui.QLineEdit(self.groupbox1)
        self.edit1_onh.setEnabled(False)
        self.edit1_onh.setObjectName(_fromUtf8("edit1_onh"))
        self.horizontalLayout_3.addWidget(self.edit1_onh)
        self.edit1_onm = QtGui.QLineEdit(self.groupbox1)
        self.edit1_onm.setEnabled(False)
        self.edit1_onm.setObjectName(_fromUtf8("edit1_onm"))
        self.horizontalLayout_3.addWidget(self.edit1_onm)
        self.edit1_ons = QtGui.QLineEdit(self.groupbox1)
        self.edit1_ons.setEnabled(False)
        self.edit1_ons.setObjectName(_fromUtf8("edit1_ons"))
        self.horizontalLayout_3.addWidget(self.edit1_ons)
        self.line_7 = QtGui.QFrame(self.groupbox1)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout_3.addWidget(self.line_7)
        self.edit1_offh = QtGui.QLineEdit(self.groupbox1)
        self.edit1_offh.setEnabled(False)
        self.edit1_offh.setObjectName(_fromUtf8("edit1_offh"))
        self.horizontalLayout_3.addWidget(self.edit1_offh)
        self.edit1_offm = QtGui.QLineEdit(self.groupbox1)
        self.edit1_offm.setEnabled(False)
        self.edit1_offm.setObjectName(_fromUtf8("edit1_offm"))
        self.horizontalLayout_3.addWidget(self.edit1_offm)
        self.edit1_offs = QtGui.QLineEdit(self.groupbox1)
        self.edit1_offs.setEnabled(False)
        self.edit1_offs.setPlaceholderText(_fromUtf8(""))
        self.edit1_offs.setObjectName(_fromUtf8("edit1_offs"))
        self.horizontalLayout_3.addWidget(self.edit1_offs)
        self.line_8 = QtGui.QFrame(self.groupbox1)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout_3.addWidget(self.line_8)
        self.edit1_totalh = QtGui.QLineEdit(self.groupbox1)
        self.edit1_totalh.setEnabled(False)
        self.edit1_totalh.setPlaceholderText(_fromUtf8(""))
        self.edit1_totalh.setObjectName(_fromUtf8("edit1_totalh"))
        self.horizontalLayout_3.addWidget(self.edit1_totalh)
        self.edit1_totalm = QtGui.QLineEdit(self.groupbox1)
        self.edit1_totalm.setEnabled(False)
        self.edit1_totalm.setPlaceholderText(_fromUtf8(""))
        self.edit1_totalm.setObjectName(_fromUtf8("edit1_totalm"))
        self.horizontalLayout_3.addWidget(self.edit1_totalm)
        self.edit1_totals = QtGui.QLineEdit(self.groupbox1)
        self.edit1_totals.setEnabled(False)
        self.edit1_totals.setPlaceholderText(_fromUtf8(""))
        self.edit1_totals.setObjectName(_fromUtf8("edit1_totals"))
        self.horizontalLayout_3.addWidget(self.edit1_totals)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupbox1)
        self.groupbox2 = QtGui.QGroupBox(self.groupBox_3)
        self.groupbox2.setAutoFillBackground(False)
        self.groupbox2.setStyleSheet(_fromUtf8("QGroupBox {\n"
"  border: 2px solid;\n"
"  border-color: rgba(255, 255, 255, 0);\n"
"}"))
        self.groupbox2.setTitle(_fromUtf8(""))
        self.groupbox2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupbox2.setObjectName(_fromUtf8("groupbox2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupbox2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.valve2 = QtGui.QPushButton(self.groupbox2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valve2.sizePolicy().hasHeightForWidth())
        self.valve2.setSizePolicy(sizePolicy)
        self.valve2.setCheckable(True)
        self.valve2.setObjectName(_fromUtf8("valve2"))
        self.horizontalLayout_9.addWidget(self.valve2)
        self.line_11 = QtGui.QFrame(self.groupbox2)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.horizontalLayout_9.addWidget(self.line_11)
        self.edit2_delayh = QtGui.QLineEdit(self.groupbox2)
        self.edit2_delayh.setEnabled(False)
        self.edit2_delayh.setStyleSheet(_fromUtf8(""))
        self.edit2_delayh.setObjectName(_fromUtf8("edit2_delayh"))
        self.horizontalLayout_9.addWidget(self.edit2_delayh)
        self.edit2_delaym = QtGui.QLineEdit(self.groupbox2)
        self.edit2_delaym.setEnabled(False)
        self.edit2_delaym.setObjectName(_fromUtf8("edit2_delaym"))
        self.horizontalLayout_9.addWidget(self.edit2_delaym)
        self.edit2_delays = QtGui.QLineEdit(self.groupbox2)
        self.edit2_delays.setEnabled(False)
        self.edit2_delays.setObjectName(_fromUtf8("edit2_delays"))
        self.horizontalLayout_9.addWidget(self.edit2_delays)
        self.line_12 = QtGui.QFrame(self.groupbox2)
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.horizontalLayout_9.addWidget(self.line_12)
        self.edit2_onh = QtGui.QLineEdit(self.groupbox2)
        self.edit2_onh.setEnabled(False)
        self.edit2_onh.setObjectName(_fromUtf8("edit2_onh"))
        self.horizontalLayout_9.addWidget(self.edit2_onh)
        self.edit2_onm = QtGui.QLineEdit(self.groupbox2)
        self.edit2_onm.setEnabled(False)
        self.edit2_onm.setObjectName(_fromUtf8("edit2_onm"))
        self.horizontalLayout_9.addWidget(self.edit2_onm)
        self.edit2_ons = QtGui.QLineEdit(self.groupbox2)
        self.edit2_ons.setEnabled(False)
        self.edit2_ons.setObjectName(_fromUtf8("edit2_ons"))
        self.horizontalLayout_9.addWidget(self.edit2_ons)
        self.line_13 = QtGui.QFrame(self.groupbox2)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.horizontalLayout_9.addWidget(self.line_13)
        self.edit2_offh = QtGui.QLineEdit(self.groupbox2)
        self.edit2_offh.setEnabled(False)
        self.edit2_offh.setObjectName(_fromUtf8("edit2_offh"))
        self.horizontalLayout_9.addWidget(self.edit2_offh)
        self.edit2_offm = QtGui.QLineEdit(self.groupbox2)
        self.edit2_offm.setEnabled(False)
        self.edit2_offm.setObjectName(_fromUtf8("edit2_offm"))
        self.horizontalLayout_9.addWidget(self.edit2_offm)
        self.edit2_offs = QtGui.QLineEdit(self.groupbox2)
        self.edit2_offs.setEnabled(False)
        self.edit2_offs.setPlaceholderText(_fromUtf8(""))
        self.edit2_offs.setObjectName(_fromUtf8("edit2_offs"))
        self.horizontalLayout_9.addWidget(self.edit2_offs)
        self.line_14 = QtGui.QFrame(self.groupbox2)
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.horizontalLayout_9.addWidget(self.line_14)
        self.edit2_totalh = QtGui.QLineEdit(self.groupbox2)
        self.edit2_totalh.setEnabled(False)
        self.edit2_totalh.setPlaceholderText(_fromUtf8(""))
        self.edit2_totalh.setObjectName(_fromUtf8("edit2_totalh"))
        self.horizontalLayout_9.addWidget(self.edit2_totalh)
        self.edit2_totalm = QtGui.QLineEdit(self.groupbox2)
        self.edit2_totalm.setEnabled(False)
        self.edit2_totalm.setPlaceholderText(_fromUtf8(""))
        self.edit2_totalm.setObjectName(_fromUtf8("edit2_totalm"))
        self.horizontalLayout_9.addWidget(self.edit2_totalm)
        self.edit2_totals = QtGui.QLineEdit(self.groupbox2)
        self.edit2_totals.setEnabled(False)
        self.edit2_totals.setPlaceholderText(_fromUtf8(""))
        self.edit2_totals.setObjectName(_fromUtf8("edit2_totals"))
        self.horizontalLayout_9.addWidget(self.edit2_totals)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addWidget(self.groupbox2)
        self.groupbox3 = QtGui.QGroupBox(self.groupBox_3)
        self.groupbox3.setAutoFillBackground(False)
        self.groupbox3.setStyleSheet(_fromUtf8("QGroupBox {\n"
"  border: 2px solid;\n"
"  border-color: rgba(255, 255, 255, 0);\n"
"}"))
        self.groupbox3.setTitle(_fromUtf8(""))
        self.groupbox3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupbox3.setObjectName(_fromUtf8("groupbox3"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupbox3)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.valve3 = QtGui.QPushButton(self.groupbox3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valve3.sizePolicy().hasHeightForWidth())
        self.valve3.setSizePolicy(sizePolicy)
        self.valve3.setCheckable(True)
        self.valve3.setObjectName(_fromUtf8("valve3"))
        self.horizontalLayout_13.addWidget(self.valve3)
        self.line_19 = QtGui.QFrame(self.groupbox3)
        self.line_19.setFrameShape(QtGui.QFrame.VLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.horizontalLayout_13.addWidget(self.line_19)
        self.edit3_delayh = QtGui.QLineEdit(self.groupbox3)
        self.edit3_delayh.setEnabled(False)
        self.edit3_delayh.setStyleSheet(_fromUtf8(""))
        self.edit3_delayh.setObjectName(_fromUtf8("edit3_delayh"))
        self.horizontalLayout_13.addWidget(self.edit3_delayh)
        self.edit3_delaym = QtGui.QLineEdit(self.groupbox3)
        self.edit3_delaym.setEnabled(False)
        self.edit3_delaym.setObjectName(_fromUtf8("edit3_delaym"))
        self.horizontalLayout_13.addWidget(self.edit3_delaym)
        self.edit3_delays = QtGui.QLineEdit(self.groupbox3)
        self.edit3_delays.setEnabled(False)
        self.edit3_delays.setObjectName(_fromUtf8("edit3_delays"))
        self.horizontalLayout_13.addWidget(self.edit3_delays)
        self.line_20 = QtGui.QFrame(self.groupbox3)
        self.line_20.setFrameShape(QtGui.QFrame.VLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.horizontalLayout_13.addWidget(self.line_20)
        self.edit3_onh = QtGui.QLineEdit(self.groupbox3)
        self.edit3_onh.setEnabled(False)
        self.edit3_onh.setObjectName(_fromUtf8("edit3_onh"))
        self.horizontalLayout_13.addWidget(self.edit3_onh)
        self.edit3_onm = QtGui.QLineEdit(self.groupbox3)
        self.edit3_onm.setEnabled(False)
        self.edit3_onm.setObjectName(_fromUtf8("edit3_onm"))
        self.horizontalLayout_13.addWidget(self.edit3_onm)
        self.edit3_ons = QtGui.QLineEdit(self.groupbox3)
        self.edit3_ons.setEnabled(False)
        self.edit3_ons.setObjectName(_fromUtf8("edit3_ons"))
        self.horizontalLayout_13.addWidget(self.edit3_ons)
        self.line_21 = QtGui.QFrame(self.groupbox3)
        self.line_21.setFrameShape(QtGui.QFrame.VLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.horizontalLayout_13.addWidget(self.line_21)
        self.edit3_offh = QtGui.QLineEdit(self.groupbox3)
        self.edit3_offh.setEnabled(False)
        self.edit3_offh.setObjectName(_fromUtf8("edit3_offh"))
        self.horizontalLayout_13.addWidget(self.edit3_offh)
        self.edit3_offm = QtGui.QLineEdit(self.groupbox3)
        self.edit3_offm.setEnabled(False)
        self.edit3_offm.setObjectName(_fromUtf8("edit3_offm"))
        self.horizontalLayout_13.addWidget(self.edit3_offm)
        self.edit3_offs = QtGui.QLineEdit(self.groupbox3)
        self.edit3_offs.setEnabled(False)
        self.edit3_offs.setPlaceholderText(_fromUtf8(""))
        self.edit3_offs.setObjectName(_fromUtf8("edit3_offs"))
        self.horizontalLayout_13.addWidget(self.edit3_offs)
        self.line_22 = QtGui.QFrame(self.groupbox3)
        self.line_22.setFrameShape(QtGui.QFrame.VLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.horizontalLayout_13.addWidget(self.line_22)
        self.edit3_totalh = QtGui.QLineEdit(self.groupbox3)
        self.edit3_totalh.setEnabled(False)
        self.edit3_totalh.setPlaceholderText(_fromUtf8(""))
        self.edit3_totalh.setObjectName(_fromUtf8("edit3_totalh"))
        self.horizontalLayout_13.addWidget(self.edit3_totalh)
        self.edit3_totalm = QtGui.QLineEdit(self.groupbox3)
        self.edit3_totalm.setEnabled(False)
        self.edit3_totalm.setPlaceholderText(_fromUtf8(""))
        self.edit3_totalm.setObjectName(_fromUtf8("edit3_totalm"))
        self.horizontalLayout_13.addWidget(self.edit3_totalm)
        self.edit3_totals = QtGui.QLineEdit(self.groupbox3)
        self.edit3_totals.setEnabled(False)
        self.edit3_totals.setPlaceholderText(_fromUtf8(""))
        self.edit3_totals.setObjectName(_fromUtf8("edit3_totals"))
        self.horizontalLayout_13.addWidget(self.edit3_totals)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addWidget(self.groupbox3)
        self.groupbox4 = QtGui.QGroupBox(self.groupBox_3)
        self.groupbox4.setAutoFillBackground(False)
        self.groupbox4.setStyleSheet(_fromUtf8("QGroupBox {\n"
"  border: 2px solid;\n"
"  border-color: rgba(255, 255, 255, 0);\n"
"}"))
        self.groupbox4.setTitle(_fromUtf8(""))
        self.groupbox4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupbox4.setObjectName(_fromUtf8("groupbox4"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupbox4)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.valve4 = QtGui.QPushButton(self.groupbox4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valve4.sizePolicy().hasHeightForWidth())
        self.valve4.setSizePolicy(sizePolicy)
        self.valve4.setCheckable(True)
        self.valve4.setObjectName(_fromUtf8("valve4"))
        self.horizontalLayout_15.addWidget(self.valve4)
        self.line_23 = QtGui.QFrame(self.groupbox4)
        self.line_23.setFrameShape(QtGui.QFrame.VLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.horizontalLayout_15.addWidget(self.line_23)
        self.edit4_delayh = QtGui.QLineEdit(self.groupbox4)
        self.edit4_delayh.setEnabled(False)
        self.edit4_delayh.setStyleSheet(_fromUtf8(""))
        self.edit4_delayh.setObjectName(_fromUtf8("edit4_delayh"))
        self.horizontalLayout_15.addWidget(self.edit4_delayh)
        self.edit4_delaym = QtGui.QLineEdit(self.groupbox4)
        self.edit4_delaym.setEnabled(False)
        self.edit4_delaym.setObjectName(_fromUtf8("edit4_delaym"))
        self.horizontalLayout_15.addWidget(self.edit4_delaym)
        self.edit4_delays = QtGui.QLineEdit(self.groupbox4)
        self.edit4_delays.setEnabled(False)
        self.edit4_delays.setObjectName(_fromUtf8("edit4_delays"))
        self.horizontalLayout_15.addWidget(self.edit4_delays)
        self.line_24 = QtGui.QFrame(self.groupbox4)
        self.line_24.setFrameShape(QtGui.QFrame.VLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.horizontalLayout_15.addWidget(self.line_24)
        self.edit4_onh = QtGui.QLineEdit(self.groupbox4)
        self.edit4_onh.setEnabled(False)
        self.edit4_onh.setObjectName(_fromUtf8("edit4_onh"))
        self.horizontalLayout_15.addWidget(self.edit4_onh)
        self.edit4_onm = QtGui.QLineEdit(self.groupbox4)
        self.edit4_onm.setEnabled(False)
        self.edit4_onm.setObjectName(_fromUtf8("edit4_onm"))
        self.horizontalLayout_15.addWidget(self.edit4_onm)
        self.edit4_ons = QtGui.QLineEdit(self.groupbox4)
        self.edit4_ons.setEnabled(False)
        self.edit4_ons.setObjectName(_fromUtf8("edit4_ons"))
        self.horizontalLayout_15.addWidget(self.edit4_ons)
        self.line_25 = QtGui.QFrame(self.groupbox4)
        self.line_25.setFrameShape(QtGui.QFrame.VLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.horizontalLayout_15.addWidget(self.line_25)
        self.edit4_offh = QtGui.QLineEdit(self.groupbox4)
        self.edit4_offh.setEnabled(False)
        self.edit4_offh.setObjectName(_fromUtf8("edit4_offh"))
        self.horizontalLayout_15.addWidget(self.edit4_offh)
        self.edit4_offm = QtGui.QLineEdit(self.groupbox4)
        self.edit4_offm.setEnabled(False)
        self.edit4_offm.setObjectName(_fromUtf8("edit4_offm"))
        self.horizontalLayout_15.addWidget(self.edit4_offm)
        self.edit4_offs = QtGui.QLineEdit(self.groupbox4)
        self.edit4_offs.setEnabled(False)
        self.edit4_offs.setPlaceholderText(_fromUtf8(""))
        self.edit4_offs.setObjectName(_fromUtf8("edit4_offs"))
        self.horizontalLayout_15.addWidget(self.edit4_offs)
        self.line_26 = QtGui.QFrame(self.groupbox4)
        self.line_26.setFrameShape(QtGui.QFrame.VLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName(_fromUtf8("line_26"))
        self.horizontalLayout_15.addWidget(self.line_26)
        self.edit4_totalh = QtGui.QLineEdit(self.groupbox4)
        self.edit4_totalh.setEnabled(False)
        self.edit4_totalh.setPlaceholderText(_fromUtf8(""))
        self.edit4_totalh.setObjectName(_fromUtf8("edit4_totalh"))
        self.horizontalLayout_15.addWidget(self.edit4_totalh)
        self.edit4_totalm = QtGui.QLineEdit(self.groupbox4)
        self.edit4_totalm.setEnabled(False)
        self.edit4_totalm.setPlaceholderText(_fromUtf8(""))
        self.edit4_totalm.setObjectName(_fromUtf8("edit4_totalm"))
        self.horizontalLayout_15.addWidget(self.edit4_totalm)
        self.edit4_totals = QtGui.QLineEdit(self.groupbox4)
        self.edit4_totals.setEnabled(False)
        self.edit4_totals.setPlaceholderText(_fromUtf8(""))
        self.edit4_totals.setObjectName(_fromUtf8("edit4_totals"))
        self.horizontalLayout_15.addWidget(self.edit4_totals)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        self.verticalLayout.addWidget(self.groupbox4)
        self.groupbox5 = QtGui.QGroupBox(self.groupBox_3)
        self.groupbox5.setAutoFillBackground(False)
        self.groupbox5.setStyleSheet(_fromUtf8("QGroupBox {\n"
"  border: 2px solid;\n"
"  border-color: rgba(255, 255, 255, 0);\n"
"}"))
        self.groupbox5.setTitle(_fromUtf8(""))
        self.groupbox5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupbox5.setObjectName(_fromUtf8("groupbox5"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.groupbox5)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.valve5 = QtGui.QPushButton(self.groupbox5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valve5.sizePolicy().hasHeightForWidth())
        self.valve5.setSizePolicy(sizePolicy)
        self.valve5.setCheckable(True)
        self.valve5.setObjectName(_fromUtf8("valve5"))
        self.horizontalLayout_17.addWidget(self.valve5)
        self.line_27 = QtGui.QFrame(self.groupbox5)
        self.line_27.setFrameShape(QtGui.QFrame.VLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName(_fromUtf8("line_27"))
        self.horizontalLayout_17.addWidget(self.line_27)
        self.edit5_delayh = QtGui.QLineEdit(self.groupbox5)
        self.edit5_delayh.setEnabled(False)
        self.edit5_delayh.setStyleSheet(_fromUtf8(""))
        self.edit5_delayh.setObjectName(_fromUtf8("edit5_delayh"))
        self.horizontalLayout_17.addWidget(self.edit5_delayh)
        self.edit5_delaym = QtGui.QLineEdit(self.groupbox5)
        self.edit5_delaym.setEnabled(False)
        self.edit5_delaym.setObjectName(_fromUtf8("edit5_delaym"))
        self.horizontalLayout_17.addWidget(self.edit5_delaym)
        self.edit5_delays = QtGui.QLineEdit(self.groupbox5)
        self.edit5_delays.setEnabled(False)
        self.edit5_delays.setObjectName(_fromUtf8("edit5_delays"))
        self.horizontalLayout_17.addWidget(self.edit5_delays)
        self.line_28 = QtGui.QFrame(self.groupbox5)
        self.line_28.setFrameShape(QtGui.QFrame.VLine)
        self.line_28.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_28.setObjectName(_fromUtf8("line_28"))
        self.horizontalLayout_17.addWidget(self.line_28)
        self.edit5_onh = QtGui.QLineEdit(self.groupbox5)
        self.edit5_onh.setEnabled(False)
        self.edit5_onh.setObjectName(_fromUtf8("edit5_onh"))
        self.horizontalLayout_17.addWidget(self.edit5_onh)
        self.edit5_onm = QtGui.QLineEdit(self.groupbox5)
        self.edit5_onm.setEnabled(False)
        self.edit5_onm.setObjectName(_fromUtf8("edit5_onm"))
        self.horizontalLayout_17.addWidget(self.edit5_onm)
        self.edit5_ons = QtGui.QLineEdit(self.groupbox5)
        self.edit5_ons.setEnabled(False)
        self.edit5_ons.setObjectName(_fromUtf8("edit5_ons"))
        self.horizontalLayout_17.addWidget(self.edit5_ons)
        self.line_29 = QtGui.QFrame(self.groupbox5)
        self.line_29.setFrameShape(QtGui.QFrame.VLine)
        self.line_29.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_29.setObjectName(_fromUtf8("line_29"))
        self.horizontalLayout_17.addWidget(self.line_29)
        self.edit5_offh = QtGui.QLineEdit(self.groupbox5)
        self.edit5_offh.setEnabled(False)
        self.edit5_offh.setObjectName(_fromUtf8("edit5_offh"))
        self.horizontalLayout_17.addWidget(self.edit5_offh)
        self.edit5_offm = QtGui.QLineEdit(self.groupbox5)
        self.edit5_offm.setEnabled(False)
        self.edit5_offm.setObjectName(_fromUtf8("edit5_offm"))
        self.horizontalLayout_17.addWidget(self.edit5_offm)
        self.edit5_offs = QtGui.QLineEdit(self.groupbox5)
        self.edit5_offs.setEnabled(False)
        self.edit5_offs.setPlaceholderText(_fromUtf8(""))
        self.edit5_offs.setObjectName(_fromUtf8("edit5_offs"))
        self.horizontalLayout_17.addWidget(self.edit5_offs)
        self.line_30 = QtGui.QFrame(self.groupbox5)
        self.line_30.setFrameShape(QtGui.QFrame.VLine)
        self.line_30.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_30.setObjectName(_fromUtf8("line_30"))
        self.horizontalLayout_17.addWidget(self.line_30)
        self.edit5_totalh = QtGui.QLineEdit(self.groupbox5)
        self.edit5_totalh.setEnabled(False)
        self.edit5_totalh.setPlaceholderText(_fromUtf8(""))
        self.edit5_totalh.setObjectName(_fromUtf8("edit5_totalh"))
        self.horizontalLayout_17.addWidget(self.edit5_totalh)
        self.edit5_totalm = QtGui.QLineEdit(self.groupbox5)
        self.edit5_totalm.setEnabled(False)
        self.edit5_totalm.setPlaceholderText(_fromUtf8(""))
        self.edit5_totalm.setObjectName(_fromUtf8("edit5_totalm"))
        self.horizontalLayout_17.addWidget(self.edit5_totalm)
        self.edit5_totals = QtGui.QLineEdit(self.groupbox5)
        self.edit5_totals.setEnabled(False)
        self.edit5_totals.setPlaceholderText(_fromUtf8(""))
        self.edit5_totals.setObjectName(_fromUtf8("edit5_totals"))
        self.horizontalLayout_17.addWidget(self.edit5_totals)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.verticalLayout.addWidget(self.groupbox5)
        self.groupbox6 = QtGui.QGroupBox(self.groupBox_3)
        self.groupbox6.setAutoFillBackground(False)
        self.groupbox6.setStyleSheet(_fromUtf8("QGroupBox {\n"
"  border: 2px solid;\n"
"  border-color: rgba(255, 255, 255, 0);\n"
"}"))
        self.groupbox6.setTitle(_fromUtf8(""))
        self.groupbox6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupbox6.setObjectName(_fromUtf8("groupbox6"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.groupbox6)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.valve6 = QtGui.QPushButton(self.groupbox6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valve6.sizePolicy().hasHeightForWidth())
        self.valve6.setSizePolicy(sizePolicy)
        self.valve6.setCheckable(True)
        self.valve6.setObjectName(_fromUtf8("valve6"))
        self.horizontalLayout_19.addWidget(self.valve6)
        self.line_31 = QtGui.QFrame(self.groupbox6)
        self.line_31.setFrameShape(QtGui.QFrame.VLine)
        self.line_31.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_31.setObjectName(_fromUtf8("line_31"))
        self.horizontalLayout_19.addWidget(self.line_31)
        self.edit6_delayh = QtGui.QLineEdit(self.groupbox6)
        self.edit6_delayh.setEnabled(False)
        self.edit6_delayh.setStyleSheet(_fromUtf8(""))
        self.edit6_delayh.setObjectName(_fromUtf8("edit6_delayh"))
        self.horizontalLayout_19.addWidget(self.edit6_delayh)
        self.edit6_delaym = QtGui.QLineEdit(self.groupbox6)
        self.edit6_delaym.setEnabled(False)
        self.edit6_delaym.setObjectName(_fromUtf8("edit6_delaym"))
        self.horizontalLayout_19.addWidget(self.edit6_delaym)
        self.edit6_delays = QtGui.QLineEdit(self.groupbox6)
        self.edit6_delays.setEnabled(False)
        self.edit6_delays.setObjectName(_fromUtf8("edit6_delays"))
        self.horizontalLayout_19.addWidget(self.edit6_delays)
        self.line_32 = QtGui.QFrame(self.groupbox6)
        self.line_32.setFrameShape(QtGui.QFrame.VLine)
        self.line_32.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_32.setObjectName(_fromUtf8("line_32"))
        self.horizontalLayout_19.addWidget(self.line_32)
        self.edit6_onh = QtGui.QLineEdit(self.groupbox6)
        self.edit6_onh.setEnabled(False)
        self.edit6_onh.setObjectName(_fromUtf8("edit6_onh"))
        self.horizontalLayout_19.addWidget(self.edit6_onh)
        self.edit6_onm = QtGui.QLineEdit(self.groupbox6)
        self.edit6_onm.setEnabled(False)
        self.edit6_onm.setObjectName(_fromUtf8("edit6_onm"))
        self.horizontalLayout_19.addWidget(self.edit6_onm)
        self.edit6_ons = QtGui.QLineEdit(self.groupbox6)
        self.edit6_ons.setEnabled(False)
        self.edit6_ons.setObjectName(_fromUtf8("edit6_ons"))
        self.horizontalLayout_19.addWidget(self.edit6_ons)
        self.line_33 = QtGui.QFrame(self.groupbox6)
        self.line_33.setFrameShape(QtGui.QFrame.VLine)
        self.line_33.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_33.setObjectName(_fromUtf8("line_33"))
        self.horizontalLayout_19.addWidget(self.line_33)
        self.edit6_offh = QtGui.QLineEdit(self.groupbox6)
        self.edit6_offh.setEnabled(False)
        self.edit6_offh.setObjectName(_fromUtf8("edit6_offh"))
        self.horizontalLayout_19.addWidget(self.edit6_offh)
        self.edit6_offm = QtGui.QLineEdit(self.groupbox6)
        self.edit6_offm.setEnabled(False)
        self.edit6_offm.setObjectName(_fromUtf8("edit6_offm"))
        self.horizontalLayout_19.addWidget(self.edit6_offm)
        self.edit6_offs = QtGui.QLineEdit(self.groupbox6)
        self.edit6_offs.setEnabled(False)
        self.edit6_offs.setPlaceholderText(_fromUtf8(""))
        self.edit6_offs.setObjectName(_fromUtf8("edit6_offs"))
        self.horizontalLayout_19.addWidget(self.edit6_offs)
        self.line_34 = QtGui.QFrame(self.groupbox6)
        self.line_34.setFrameShape(QtGui.QFrame.VLine)
        self.line_34.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_34.setObjectName(_fromUtf8("line_34"))
        self.horizontalLayout_19.addWidget(self.line_34)
        self.edit6_totalh = QtGui.QLineEdit(self.groupbox6)
        self.edit6_totalh.setEnabled(False)
        self.edit6_totalh.setPlaceholderText(_fromUtf8(""))
        self.edit6_totalh.setObjectName(_fromUtf8("edit6_totalh"))
        self.horizontalLayout_19.addWidget(self.edit6_totalh)
        self.edit6_totalm = QtGui.QLineEdit(self.groupbox6)
        self.edit6_totalm.setEnabled(False)
        self.edit6_totalm.setPlaceholderText(_fromUtf8(""))
        self.edit6_totalm.setObjectName(_fromUtf8("edit6_totalm"))
        self.horizontalLayout_19.addWidget(self.edit6_totalm)
        self.edit6_totals = QtGui.QLineEdit(self.groupbox6)
        self.edit6_totals.setEnabled(False)
        self.edit6_totals.setPlaceholderText(_fromUtf8(""))
        self.edit6_totals.setObjectName(_fromUtf8("edit6_totals"))
        self.horizontalLayout_19.addWidget(self.edit6_totals)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.verticalLayout.addWidget(self.groupbox6)
        self.groupbox7 = QtGui.QGroupBox(self.groupBox_3)
        self.groupbox7.setAutoFillBackground(False)
        self.groupbox7.setStyleSheet(_fromUtf8("QGroupBox {\n"
"  border: 2px solid;\n"
"  border-color: rgba(255, 255, 255, 0);\n"
"}"))
        self.groupbox7.setTitle(_fromUtf8(""))
        self.groupbox7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupbox7.setObjectName(_fromUtf8("groupbox7"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.groupbox7)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.valve7 = QtGui.QPushButton(self.groupbox7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valve7.sizePolicy().hasHeightForWidth())
        self.valve7.setSizePolicy(sizePolicy)
        self.valve7.setCheckable(True)
        self.valve7.setObjectName(_fromUtf8("valve7"))
        self.horizontalLayout_21.addWidget(self.valve7)
        self.line_35 = QtGui.QFrame(self.groupbox7)
        self.line_35.setFrameShape(QtGui.QFrame.VLine)
        self.line_35.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_35.setObjectName(_fromUtf8("line_35"))
        self.horizontalLayout_21.addWidget(self.line_35)
        self.edit7_delayh = QtGui.QLineEdit(self.groupbox7)
        self.edit7_delayh.setEnabled(False)
        self.edit7_delayh.setStyleSheet(_fromUtf8(""))
        self.edit7_delayh.setObjectName(_fromUtf8("edit7_delayh"))
        self.horizontalLayout_21.addWidget(self.edit7_delayh)
        self.edit7_delaym = QtGui.QLineEdit(self.groupbox7)
        self.edit7_delaym.setEnabled(False)
        self.edit7_delaym.setObjectName(_fromUtf8("edit7_delaym"))
        self.horizontalLayout_21.addWidget(self.edit7_delaym)
        self.edit7_delays = QtGui.QLineEdit(self.groupbox7)
        self.edit7_delays.setEnabled(False)
        self.edit7_delays.setObjectName(_fromUtf8("edit7_delays"))
        self.horizontalLayout_21.addWidget(self.edit7_delays)
        self.line_36 = QtGui.QFrame(self.groupbox7)
        self.line_36.setFrameShape(QtGui.QFrame.VLine)
        self.line_36.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_36.setObjectName(_fromUtf8("line_36"))
        self.horizontalLayout_21.addWidget(self.line_36)
        self.edit7_onh = QtGui.QLineEdit(self.groupbox7)
        self.edit7_onh.setEnabled(False)
        self.edit7_onh.setObjectName(_fromUtf8("edit7_onh"))
        self.horizontalLayout_21.addWidget(self.edit7_onh)
        self.edit7_onm = QtGui.QLineEdit(self.groupbox7)
        self.edit7_onm.setEnabled(False)
        self.edit7_onm.setObjectName(_fromUtf8("edit7_onm"))
        self.horizontalLayout_21.addWidget(self.edit7_onm)
        self.edit7_ons = QtGui.QLineEdit(self.groupbox7)
        self.edit7_ons.setEnabled(False)
        self.edit7_ons.setObjectName(_fromUtf8("edit7_ons"))
        self.horizontalLayout_21.addWidget(self.edit7_ons)
        self.line_37 = QtGui.QFrame(self.groupbox7)
        self.line_37.setFrameShape(QtGui.QFrame.VLine)
        self.line_37.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_37.setObjectName(_fromUtf8("line_37"))
        self.horizontalLayout_21.addWidget(self.line_37)
        self.edit7_offh = QtGui.QLineEdit(self.groupbox7)
        self.edit7_offh.setEnabled(False)
        self.edit7_offh.setObjectName(_fromUtf8("edit7_offh"))
        self.horizontalLayout_21.addWidget(self.edit7_offh)
        self.edit7_offm = QtGui.QLineEdit(self.groupbox7)
        self.edit7_offm.setEnabled(False)
        self.edit7_offm.setObjectName(_fromUtf8("edit7_offm"))
        self.horizontalLayout_21.addWidget(self.edit7_offm)
        self.edit7_offs = QtGui.QLineEdit(self.groupbox7)
        self.edit7_offs.setEnabled(False)
        self.edit7_offs.setPlaceholderText(_fromUtf8(""))
        self.edit7_offs.setObjectName(_fromUtf8("edit7_offs"))
        self.horizontalLayout_21.addWidget(self.edit7_offs)
        self.line_38 = QtGui.QFrame(self.groupbox7)
        self.line_38.setFrameShape(QtGui.QFrame.VLine)
        self.line_38.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_38.setObjectName(_fromUtf8("line_38"))
        self.horizontalLayout_21.addWidget(self.line_38)
        self.edit7_totalh = QtGui.QLineEdit(self.groupbox7)
        self.edit7_totalh.setEnabled(False)
        self.edit7_totalh.setPlaceholderText(_fromUtf8(""))
        self.edit7_totalh.setObjectName(_fromUtf8("edit7_totalh"))
        self.horizontalLayout_21.addWidget(self.edit7_totalh)
        self.edit7_totalm = QtGui.QLineEdit(self.groupbox7)
        self.edit7_totalm.setEnabled(False)
        self.edit7_totalm.setPlaceholderText(_fromUtf8(""))
        self.edit7_totalm.setObjectName(_fromUtf8("edit7_totalm"))
        self.horizontalLayout_21.addWidget(self.edit7_totalm)
        self.edit7_totals = QtGui.QLineEdit(self.groupbox7)
        self.edit7_totals.setEnabled(False)
        self.edit7_totals.setPlaceholderText(_fromUtf8(""))
        self.edit7_totals.setObjectName(_fromUtf8("edit7_totals"))
        self.horizontalLayout_21.addWidget(self.edit7_totals)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_21)
        self.verticalLayout.addWidget(self.groupbox7)
        self.groupbox8 = QtGui.QGroupBox(self.groupBox_3)
        self.groupbox8.setAutoFillBackground(False)
        self.groupbox8.setStyleSheet(_fromUtf8("QGroupBox {\n"
"  border: 2px solid;\n"
"  border-color: rgba(255, 255, 255, 0);\n"
"}"))
        self.groupbox8.setTitle(_fromUtf8(""))
        self.groupbox8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupbox8.setObjectName(_fromUtf8("groupbox8"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.groupbox8)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.valve8 = QtGui.QPushButton(self.groupbox8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valve8.sizePolicy().hasHeightForWidth())
        self.valve8.setSizePolicy(sizePolicy)
        self.valve8.setCheckable(True)
        self.valve8.setObjectName(_fromUtf8("valve8"))
        self.horizontalLayout_23.addWidget(self.valve8)
        self.line_39 = QtGui.QFrame(self.groupbox8)
        self.line_39.setFrameShape(QtGui.QFrame.VLine)
        self.line_39.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_39.setObjectName(_fromUtf8("line_39"))
        self.horizontalLayout_23.addWidget(self.line_39)
        self.edit8_delayh = QtGui.QLineEdit(self.groupbox8)
        self.edit8_delayh.setEnabled(False)
        self.edit8_delayh.setStyleSheet(_fromUtf8(""))
        self.edit8_delayh.setObjectName(_fromUtf8("edit8_delayh"))
        self.horizontalLayout_23.addWidget(self.edit8_delayh)
        self.edit8_delaym = QtGui.QLineEdit(self.groupbox8)
        self.edit8_delaym.setEnabled(False)
        self.edit8_delaym.setObjectName(_fromUtf8("edit8_delaym"))
        self.horizontalLayout_23.addWidget(self.edit8_delaym)
        self.edit8_delays = QtGui.QLineEdit(self.groupbox8)
        self.edit8_delays.setEnabled(False)
        self.edit8_delays.setObjectName(_fromUtf8("edit8_delays"))
        self.horizontalLayout_23.addWidget(self.edit8_delays)
        self.line_40 = QtGui.QFrame(self.groupbox8)
        self.line_40.setFrameShape(QtGui.QFrame.VLine)
        self.line_40.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_40.setObjectName(_fromUtf8("line_40"))
        self.horizontalLayout_23.addWidget(self.line_40)
        self.edit8_onh = QtGui.QLineEdit(self.groupbox8)
        self.edit8_onh.setEnabled(False)
        self.edit8_onh.setObjectName(_fromUtf8("edit8_onh"))
        self.horizontalLayout_23.addWidget(self.edit8_onh)
        self.edit8_onm = QtGui.QLineEdit(self.groupbox8)
        self.edit8_onm.setEnabled(False)
        self.edit8_onm.setObjectName(_fromUtf8("edit8_onm"))
        self.horizontalLayout_23.addWidget(self.edit8_onm)
        self.edit8_ons = QtGui.QLineEdit(self.groupbox8)
        self.edit8_ons.setEnabled(False)
        self.edit8_ons.setObjectName(_fromUtf8("edit8_ons"))
        self.horizontalLayout_23.addWidget(self.edit8_ons)
        self.line_41 = QtGui.QFrame(self.groupbox8)
        self.line_41.setFrameShape(QtGui.QFrame.VLine)
        self.line_41.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_41.setObjectName(_fromUtf8("line_41"))
        self.horizontalLayout_23.addWidget(self.line_41)
        self.edit8_offh = QtGui.QLineEdit(self.groupbox8)
        self.edit8_offh.setEnabled(False)
        self.edit8_offh.setObjectName(_fromUtf8("edit8_offh"))
        self.horizontalLayout_23.addWidget(self.edit8_offh)
        self.edit8_offm = QtGui.QLineEdit(self.groupbox8)
        self.edit8_offm.setEnabled(False)
        self.edit8_offm.setObjectName(_fromUtf8("edit8_offm"))
        self.horizontalLayout_23.addWidget(self.edit8_offm)
        self.edit8_offs = QtGui.QLineEdit(self.groupbox8)
        self.edit8_offs.setEnabled(False)
        self.edit8_offs.setPlaceholderText(_fromUtf8(""))
        self.edit8_offs.setObjectName(_fromUtf8("edit8_offs"))
        self.horizontalLayout_23.addWidget(self.edit8_offs)
        self.line_42 = QtGui.QFrame(self.groupbox8)
        self.line_42.setFrameShape(QtGui.QFrame.VLine)
        self.line_42.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_42.setObjectName(_fromUtf8("line_42"))
        self.horizontalLayout_23.addWidget(self.line_42)
        self.edit8_totalh = QtGui.QLineEdit(self.groupbox8)
        self.edit8_totalh.setEnabled(False)
        self.edit8_totalh.setPlaceholderText(_fromUtf8(""))
        self.edit8_totalh.setObjectName(_fromUtf8("edit8_totalh"))
        self.horizontalLayout_23.addWidget(self.edit8_totalh)
        self.edit8_totalm = QtGui.QLineEdit(self.groupbox8)
        self.edit8_totalm.setEnabled(False)
        self.edit8_totalm.setPlaceholderText(_fromUtf8(""))
        self.edit8_totalm.setObjectName(_fromUtf8("edit8_totalm"))
        self.horizontalLayout_23.addWidget(self.edit8_totalm)
        self.edit8_totals = QtGui.QLineEdit(self.groupbox8)
        self.edit8_totals.setEnabled(False)
        self.edit8_totals.setPlaceholderText(_fromUtf8(""))
        self.edit8_totals.setObjectName(_fromUtf8("edit8_totals"))
        self.horizontalLayout_23.addWidget(self.edit8_totals)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_23)
        self.verticalLayout.addWidget(self.groupbox8)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 653, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Archivo = QtGui.QMenu(self.menubar)
        self.menu_Archivo.setObjectName(_fromUtf8("menu_Archivo"))
        self.menuA_yuda = QtGui.QMenu(self.menubar)
        self.menuA_yuda.setObjectName(_fromUtf8("menuA_yuda"))
        self.menuPrograma = QtGui.QMenu(self.menubar)
        self.menuPrograma.setObjectName(_fromUtf8("menuPrograma"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar1 = QtGui.QStatusBar(MainWindow)
        self.statusBar1.setObjectName(_fromUtf8("statusBar1"))
        MainWindow.setStatusBar(self.statusBar1)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar_2.sizePolicy().hasHeightForWidth())
        self.toolBar_2.setSizePolicy(sizePolicy)
        self.toolBar_2.setMovable(False)
        self.toolBar_2.setIconSize(QtCore.QSize(24, 24))
        self.toolBar_2.setFloatable(False)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar_2)
        self.action_Limpiar = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Limpiar.setIcon(icon1)
        self.action_Limpiar.setObjectName(_fromUtf8("action_Limpiar"))
        self.action_Salir = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Salir.setIcon(icon2)
        self.action_Salir.setObjectName(_fromUtf8("action_Salir"))
        self.action_Abrir = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Abrir.setIcon(icon3)
        self.action_Abrir.setObjectName(_fromUtf8("action_Abrir"))
        self.actionVAL_508_Ayuda = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVAL_508_Ayuda.setIcon(icon4)
        self.actionVAL_508_Ayuda.setObjectName(_fromUtf8("actionVAL_508_Ayuda"))
        self.actionAcerca_de_VAL_508 = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAcerca_de_VAL_508.setIcon(icon5)
        self.actionAcerca_de_VAL_508.setObjectName(_fromUtf8("actionAcerca_de_VAL_508"))
        self.action_Guardar = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Guardar.setIcon(icon6)
        self.action_Guardar.setObjectName(_fromUtf8("action_Guardar"))
        self.actionGuardar_Como = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/save_as.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardar_Como.setIcon(icon7)
        self.actionGuardar_Como.setObjectName(_fromUtf8("actionGuardar_Como"))
        self.action_Ejecutar = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Ejecutar.setIcon(icon8)
        self.action_Ejecutar.setObjectName(_fromUtf8("action_Ejecutar"))
        self.action_Para_Valvulas = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Para_Valvulas.setIcon(icon9)
        self.action_Para_Valvulas.setObjectName(_fromUtf8("action_Para_Valvulas"))
        self.action_Detener_USB = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/close_usb.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Detener_USB.setIcon(icon10)
        self.action_Detener_USB.setObjectName(_fromUtf8("action_Detener_USB"))
        self.actionPreferencias = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/preferences.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferencias.setIcon(icon11)
        self.actionPreferencias.setObjectName(_fromUtf8("actionPreferencias"))
        self.actionArchivo_Nuevo = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/new_file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionArchivo_Nuevo.setIcon(icon12)
        self.actionArchivo_Nuevo.setObjectName(_fromUtf8("actionArchivo_Nuevo"))
        self.menu_Archivo.addAction(self.actionArchivo_Nuevo)
        self.menu_Archivo.addAction(self.action_Abrir)
        self.menu_Archivo.addAction(self.action_Guardar)
        self.menu_Archivo.addAction(self.actionGuardar_Como)
        self.menu_Archivo.addSeparator()
        self.menu_Archivo.addAction(self.action_Limpiar)
        self.menu_Archivo.addSeparator()
        self.menu_Archivo.addAction(self.action_Salir)
        self.menuA_yuda.addAction(self.actionVAL_508_Ayuda)
        self.menuA_yuda.addSeparator()
        self.menuA_yuda.addAction(self.actionAcerca_de_VAL_508)
        self.menuPrograma.addAction(self.action_Ejecutar)
        self.menuPrograma.addAction(self.action_Para_Valvulas)
        self.menuPrograma.addAction(self.action_Detener_USB)
        self.menubar.addAction(self.menu_Archivo.menuAction())
        self.menubar.addAction(self.menuPrograma.menuAction())
        self.menubar.addAction(self.menuA_yuda.menuAction())
        self.toolBar.addAction(self.actionArchivo_Nuevo)
        self.toolBar.addAction(self.action_Abrir)
        self.toolBar.addAction(self.action_Guardar)
        self.toolBar.addAction(self.action_Limpiar)
        self.toolBar.addAction(self.actionVAL_508_Ayuda)
        self.toolBar.addAction(self.action_Salir)
        self.toolBar.addSeparator()
        self.toolBar_2.addAction(self.action_Ejecutar)
        self.toolBar_2.addAction(self.action_Para_Valvulas)
        self.toolBar_2.addAction(self.action_Detener_USB)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Val 508", None))
        self.label.setText(_translate("MainWindow", "Valvula", None))
        self.label_2.setText(_translate("MainWindow", "Delay", None))
        self.label_3.setText(_translate("MainWindow", "On", None))
        self.label_4.setText(_translate("MainWindow", "Off", None))
        self.label_5.setText(_translate("MainWindow", "Total", None))
        self.valve1.setText(_translate("MainWindow", "&1", None))
        self.edit1_delayh.setText(_translate("MainWindow", "0", None))
        self.edit1_delaym.setText(_translate("MainWindow", "0", None))
        self.edit1_delays.setText(_translate("MainWindow", "0", None))
        self.edit1_onh.setText(_translate("MainWindow", "0", None))
        self.edit1_onm.setText(_translate("MainWindow", "0", None))
        self.edit1_ons.setText(_translate("MainWindow", "0", None))
        self.edit1_offh.setText(_translate("MainWindow", "0", None))
        self.edit1_offm.setText(_translate("MainWindow", "0", None))
        self.edit1_offs.setText(_translate("MainWindow", "0", None))
        self.edit1_totalh.setText(_translate("MainWindow", "0", None))
        self.edit1_totalm.setText(_translate("MainWindow", "0", None))
        self.edit1_totals.setText(_translate("MainWindow", "0", None))
        self.valve2.setText(_translate("MainWindow", "&2", None))
        self.edit2_delayh.setText(_translate("MainWindow", "0", None))
        self.edit2_delaym.setText(_translate("MainWindow", "0", None))
        self.edit2_delays.setText(_translate("MainWindow", "0", None))
        self.edit2_onh.setText(_translate("MainWindow", "0", None))
        self.edit2_onm.setText(_translate("MainWindow", "0", None))
        self.edit2_ons.setText(_translate("MainWindow", "0", None))
        self.edit2_offh.setText(_translate("MainWindow", "0", None))
        self.edit2_offm.setText(_translate("MainWindow", "0", None))
        self.edit2_offs.setText(_translate("MainWindow", "0", None))
        self.edit2_totalh.setText(_translate("MainWindow", "0", None))
        self.edit2_totalm.setText(_translate("MainWindow", "0", None))
        self.edit2_totals.setText(_translate("MainWindow", "0", None))
        self.valve3.setText(_translate("MainWindow", "&3", None))
        self.edit3_delayh.setText(_translate("MainWindow", "0", None))
        self.edit3_delaym.setText(_translate("MainWindow", "0", None))
        self.edit3_delays.setText(_translate("MainWindow", "0", None))
        self.edit3_onh.setText(_translate("MainWindow", "0", None))
        self.edit3_onm.setText(_translate("MainWindow", "0", None))
        self.edit3_ons.setText(_translate("MainWindow", "0", None))
        self.edit3_offh.setText(_translate("MainWindow", "0", None))
        self.edit3_offm.setText(_translate("MainWindow", "0", None))
        self.edit3_offs.setText(_translate("MainWindow", "0", None))
        self.edit3_totalh.setText(_translate("MainWindow", "0", None))
        self.edit3_totalm.setText(_translate("MainWindow", "0", None))
        self.edit3_totals.setText(_translate("MainWindow", "0", None))
        self.valve4.setText(_translate("MainWindow", "&4", None))
        self.edit4_delayh.setText(_translate("MainWindow", "0", None))
        self.edit4_delaym.setText(_translate("MainWindow", "0", None))
        self.edit4_delays.setText(_translate("MainWindow", "0", None))
        self.edit4_onh.setText(_translate("MainWindow", "0", None))
        self.edit4_onm.setText(_translate("MainWindow", "0", None))
        self.edit4_ons.setText(_translate("MainWindow", "0", None))
        self.edit4_offh.setText(_translate("MainWindow", "0", None))
        self.edit4_offm.setText(_translate("MainWindow", "0", None))
        self.edit4_offs.setText(_translate("MainWindow", "0", None))
        self.edit4_totalh.setText(_translate("MainWindow", "0", None))
        self.edit4_totalm.setText(_translate("MainWindow", "0", None))
        self.edit4_totals.setText(_translate("MainWindow", "0", None))
        self.valve5.setText(_translate("MainWindow", "&5", None))
        self.edit5_delayh.setText(_translate("MainWindow", "0", None))
        self.edit5_delaym.setText(_translate("MainWindow", "0", None))
        self.edit5_delays.setText(_translate("MainWindow", "0", None))
        self.edit5_onh.setText(_translate("MainWindow", "0", None))
        self.edit5_onm.setText(_translate("MainWindow", "0", None))
        self.edit5_ons.setText(_translate("MainWindow", "0", None))
        self.edit5_offh.setText(_translate("MainWindow", "0", None))
        self.edit5_offm.setText(_translate("MainWindow", "0", None))
        self.edit5_offs.setText(_translate("MainWindow", "0", None))
        self.edit5_totalh.setText(_translate("MainWindow", "0", None))
        self.edit5_totalm.setText(_translate("MainWindow", "0", None))
        self.edit5_totals.setText(_translate("MainWindow", "0", None))
        self.valve6.setText(_translate("MainWindow", "&6", None))
        self.edit6_delayh.setText(_translate("MainWindow", "0", None))
        self.edit6_delaym.setText(_translate("MainWindow", "0", None))
        self.edit6_delays.setText(_translate("MainWindow", "0", None))
        self.edit6_onh.setText(_translate("MainWindow", "0", None))
        self.edit6_onm.setText(_translate("MainWindow", "0", None))
        self.edit6_ons.setText(_translate("MainWindow", "0", None))
        self.edit6_offh.setText(_translate("MainWindow", "0", None))
        self.edit6_offm.setText(_translate("MainWindow", "0", None))
        self.edit6_offs.setText(_translate("MainWindow", "0", None))
        self.edit6_totalh.setText(_translate("MainWindow", "0", None))
        self.edit6_totalm.setText(_translate("MainWindow", "0", None))
        self.edit6_totals.setText(_translate("MainWindow", "0", None))
        self.valve7.setText(_translate("MainWindow", "&7", None))
        self.edit7_delayh.setText(_translate("MainWindow", "0", None))
        self.edit7_delaym.setText(_translate("MainWindow", "0", None))
        self.edit7_delays.setText(_translate("MainWindow", "0", None))
        self.edit7_onh.setText(_translate("MainWindow", "0", None))
        self.edit7_onm.setText(_translate("MainWindow", "0", None))
        self.edit7_ons.setText(_translate("MainWindow", "0", None))
        self.edit7_offh.setText(_translate("MainWindow", "0", None))
        self.edit7_offm.setText(_translate("MainWindow", "0", None))
        self.edit7_offs.setText(_translate("MainWindow", "0", None))
        self.edit7_totalh.setText(_translate("MainWindow", "0", None))
        self.edit7_totalm.setText(_translate("MainWindow", "0", None))
        self.edit7_totals.setText(_translate("MainWindow", "0", None))
        self.valve8.setText(_translate("MainWindow", "&8", None))
        self.edit8_delayh.setText(_translate("MainWindow", "0", None))
        self.edit8_delaym.setText(_translate("MainWindow", "0", None))
        self.edit8_delays.setText(_translate("MainWindow", "0", None))
        self.edit8_onh.setText(_translate("MainWindow", "0", None))
        self.edit8_onm.setText(_translate("MainWindow", "0", None))
        self.edit8_ons.setText(_translate("MainWindow", "0", None))
        self.edit8_offh.setText(_translate("MainWindow", "0", None))
        self.edit8_offm.setText(_translate("MainWindow", "0", None))
        self.edit8_offs.setText(_translate("MainWindow", "0", None))
        self.edit8_totalh.setText(_translate("MainWindow", "0", None))
        self.edit8_totalm.setText(_translate("MainWindow", "0", None))
        self.edit8_totals.setText(_translate("MainWindow", "0", None))
        self.menu_Archivo.setTitle(_translate("MainWindow", "&Archivo", None))
        self.menuA_yuda.setTitle(_translate("MainWindow", "A&yuda", None))
        self.menuPrograma.setTitle(_translate("MainWindow", "P&rograma", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.action_Limpiar.setText(_translate("MainWindow", "&Limpiar", None))
        self.action_Salir.setText(_translate("MainWindow", "&Salir", None))
        self.action_Abrir.setText(_translate("MainWindow", "&Abrir", None))
        self.actionVAL_508_Ayuda.setText(_translate("MainWindow", "VAL 508 &Ayuda", None))
        self.actionAcerca_de_VAL_508.setText(_translate("MainWindow", "A&cerca de VAL 508", None))
        self.action_Guardar.setText(_translate("MainWindow", "&Guardar", None))
        self.actionGuardar_Como.setText(_translate("MainWindow", "Guardar &Como", None))
        self.action_Ejecutar.setText(_translate("MainWindow", "&Ejecutar", None))
        self.action_Para_Valvulas.setText(_translate("MainWindow", "&Parar Valvulas", None))
        self.action_Detener_USB.setText(_translate("MainWindow", "&Cerrar Conexión", None))
        self.actionPreferencias.setText(_translate("MainWindow", "&Preferencias", None))
        self.actionArchivo_Nuevo.setText(_translate("MainWindow", "Archivo &Nuevo", None))

import resources_rc
