# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Valvulas.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ValvulasMainWindow(object):
    def setupUi(self, ValvulasMainWindow):
        ValvulasMainWindow.setObjectName(_fromUtf8("ValvulasMainWindow"))
        ValvulasMainWindow.resize(620, 640)
        ValvulasMainWindow.setMinimumSize(QtCore.QSize(620, 640))
        ValvulasMainWindow.setMaximumSize(QtCore.QSize(620, 640))
        self.centralwidget = QtGui.QWidget(ValvulasMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.valve1 = QtGui.QPushButton(self.centralwidget)
        self.valve1.setGeometry(QtCore.QRect(30, 40, 31, 31))
        self.valve1.setCheckable(True)
        self.valve1.setChecked(False)
        self.valve1.setObjectName(_fromUtf8("valve1"))
        self.valve2 = QtGui.QPushButton(self.centralwidget)
        self.valve2.setGeometry(QtCore.QRect(30, 100, 31, 31))
        self.valve2.setCheckable(True)
        self.valve2.setObjectName(_fromUtf8("valve2"))
        self.valve3 = QtGui.QPushButton(self.centralwidget)
        self.valve3.setGeometry(QtCore.QRect(30, 160, 31, 31))
        self.valve3.setCheckable(True)
        self.valve3.setObjectName(_fromUtf8("valve3"))
        self.valve4 = QtGui.QPushButton(self.centralwidget)
        self.valve4.setGeometry(QtCore.QRect(30, 220, 31, 31))
        self.valve4.setCheckable(True)
        self.valve4.setObjectName(_fromUtf8("valve4"))
        self.valve5 = QtGui.QPushButton(self.centralwidget)
        self.valve5.setGeometry(QtCore.QRect(30, 280, 31, 31))
        self.valve5.setCheckable(True)
        self.valve5.setObjectName(_fromUtf8("valve5"))
        self.valve6 = QtGui.QPushButton(self.centralwidget)
        self.valve6.setGeometry(QtCore.QRect(30, 340, 31, 31))
        self.valve6.setCheckable(True)
        self.valve6.setObjectName(_fromUtf8("valve6"))
        self.valve7 = QtGui.QPushButton(self.centralwidget)
        self.valve7.setGeometry(QtCore.QRect(30, 400, 31, 31))
        self.valve7.setCheckable(True)
        self.valve7.setObjectName(_fromUtf8("valve7"))
        self.valve8 = QtGui.QPushButton(self.centralwidget)
        self.valve8.setGeometry(QtCore.QRect(30, 460, 31, 31))
        self.valve8.setCheckable(True)
        self.valve8.setObjectName(_fromUtf8("valve8"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 64, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 10, 64, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 10, 64, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 10, 64, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.edit1_delayh = QtGui.QLineEdit(self.centralwidget)
        self.edit1_delayh.setEnabled(False)
        self.edit1_delayh.setGeometry(QtCore.QRect(100, 40, 31, 32))
        self.edit1_delayh.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit1_delayh.setInputMask(_fromUtf8(""))
        self.edit1_delayh.setMaxLength(32767)
        self.edit1_delayh.setObjectName(_fromUtf8("edit1_delayh"))
        self.edit1_delaym = QtGui.QLineEdit(self.centralwidget)
        self.edit1_delaym.setEnabled(False)
        self.edit1_delaym.setGeometry(QtCore.QRect(130, 40, 31, 32))
        self.edit1_delaym.setInputMask(_fromUtf8(""))
        self.edit1_delaym.setMaxLength(32767)
        self.edit1_delaym.setObjectName(_fromUtf8("edit1_delaym"))
        self.edit1_onh = QtGui.QLineEdit(self.centralwidget)
        self.edit1_onh.setEnabled(False)
        self.edit1_onh.setGeometry(QtCore.QRect(230, 40, 31, 32))
        self.edit1_onh.setObjectName(_fromUtf8("edit1_onh"))
        self.edit1_onm = QtGui.QLineEdit(self.centralwidget)
        self.edit1_onm.setEnabled(False)
        self.edit1_onm.setGeometry(QtCore.QRect(260, 40, 31, 32))
        self.edit1_onm.setObjectName(_fromUtf8("edit1_onm"))
        self.edit1_offh = QtGui.QLineEdit(self.centralwidget)
        self.edit1_offh.setEnabled(False)
        self.edit1_offh.setGeometry(QtCore.QRect(360, 40, 31, 32))
        self.edit1_offh.setObjectName(_fromUtf8("edit1_offh"))
        self.edit1_offm = QtGui.QLineEdit(self.centralwidget)
        self.edit1_offm.setEnabled(False)
        self.edit1_offm.setGeometry(QtCore.QRect(390, 40, 31, 32))
        self.edit1_offm.setObjectName(_fromUtf8("edit1_offm"))
        self.edit1_totalh = QtGui.QLineEdit(self.centralwidget)
        self.edit1_totalh.setEnabled(False)
        self.edit1_totalh.setGeometry(QtCore.QRect(490, 40, 31, 32))
        self.edit1_totalh.setReadOnly(False)
        self.edit1_totalh.setObjectName(_fromUtf8("edit1_totalh"))
        self.edit1_totalm = QtGui.QLineEdit(self.centralwidget)
        self.edit1_totalm.setEnabled(False)
        self.edit1_totalm.setGeometry(QtCore.QRect(520, 40, 31, 32))
        self.edit1_totalm.setObjectName(_fromUtf8("edit1_totalm"))
        self.edit2_onh = QtGui.QLineEdit(self.centralwidget)
        self.edit2_onh.setEnabled(False)
        self.edit2_onh.setGeometry(QtCore.QRect(230, 100, 31, 32))
        self.edit2_onh.setObjectName(_fromUtf8("edit2_onh"))
        self.edit2_offh = QtGui.QLineEdit(self.centralwidget)
        self.edit2_offh.setEnabled(False)
        self.edit2_offh.setGeometry(QtCore.QRect(360, 100, 31, 32))
        self.edit2_offh.setObjectName(_fromUtf8("edit2_offh"))
        self.edit2_totalh = QtGui.QLineEdit(self.centralwidget)
        self.edit2_totalh.setEnabled(False)
        self.edit2_totalh.setGeometry(QtCore.QRect(490, 100, 31, 32))
        self.edit2_totalh.setObjectName(_fromUtf8("edit2_totalh"))
        self.edit2_onm = QtGui.QLineEdit(self.centralwidget)
        self.edit2_onm.setEnabled(False)
        self.edit2_onm.setGeometry(QtCore.QRect(260, 100, 31, 32))
        self.edit2_onm.setObjectName(_fromUtf8("edit2_onm"))
        self.edit2_totalm = QtGui.QLineEdit(self.centralwidget)
        self.edit2_totalm.setEnabled(False)
        self.edit2_totalm.setGeometry(QtCore.QRect(520, 100, 31, 32))
        self.edit2_totalm.setObjectName(_fromUtf8("edit2_totalm"))
        self.edit2_delayh = QtGui.QLineEdit(self.centralwidget)
        self.edit2_delayh.setEnabled(False)
        self.edit2_delayh.setGeometry(QtCore.QRect(100, 100, 31, 32))
        self.edit2_delayh.setInputMask(_fromUtf8(""))
        self.edit2_delayh.setMaxLength(32767)
        self.edit2_delayh.setObjectName(_fromUtf8("edit2_delayh"))
        self.edit2_delaym = QtGui.QLineEdit(self.centralwidget)
        self.edit2_delaym.setEnabled(False)
        self.edit2_delaym.setGeometry(QtCore.QRect(130, 100, 31, 32))
        self.edit2_delaym.setInputMask(_fromUtf8(""))
        self.edit2_delaym.setMaxLength(32767)
        self.edit2_delaym.setObjectName(_fromUtf8("edit2_delaym"))
        self.edit2_offm = QtGui.QLineEdit(self.centralwidget)
        self.edit2_offm.setEnabled(False)
        self.edit2_offm.setGeometry(QtCore.QRect(390, 100, 31, 32))
        self.edit2_offm.setObjectName(_fromUtf8("edit2_offm"))
        self.edit3_onh = QtGui.QLineEdit(self.centralwidget)
        self.edit3_onh.setEnabled(False)
        self.edit3_onh.setGeometry(QtCore.QRect(230, 160, 31, 32))
        self.edit3_onh.setObjectName(_fromUtf8("edit3_onh"))
        self.edit3_totalm = QtGui.QLineEdit(self.centralwidget)
        self.edit3_totalm.setEnabled(False)
        self.edit3_totalm.setGeometry(QtCore.QRect(520, 160, 31, 32))
        self.edit3_totalm.setObjectName(_fromUtf8("edit3_totalm"))
        self.edit3_totalh = QtGui.QLineEdit(self.centralwidget)
        self.edit3_totalh.setEnabled(False)
        self.edit3_totalh.setGeometry(QtCore.QRect(490, 160, 31, 32))
        self.edit3_totalh.setObjectName(_fromUtf8("edit3_totalh"))
        self.edit3_delayh = QtGui.QLineEdit(self.centralwidget)
        self.edit3_delayh.setEnabled(False)
        self.edit3_delayh.setGeometry(QtCore.QRect(100, 160, 31, 32))
        self.edit3_delayh.setInputMask(_fromUtf8(""))
        self.edit3_delayh.setMaxLength(32767)
        self.edit3_delayh.setObjectName(_fromUtf8("edit3_delayh"))
        self.edit3_offm = QtGui.QLineEdit(self.centralwidget)
        self.edit3_offm.setEnabled(False)
        self.edit3_offm.setGeometry(QtCore.QRect(390, 160, 31, 32))
        self.edit3_offm.setObjectName(_fromUtf8("edit3_offm"))
        self.edit3_offh = QtGui.QLineEdit(self.centralwidget)
        self.edit3_offh.setEnabled(False)
        self.edit3_offh.setGeometry(QtCore.QRect(360, 160, 31, 32))
        self.edit3_offh.setObjectName(_fromUtf8("edit3_offh"))
        self.edit3_onm = QtGui.QLineEdit(self.centralwidget)
        self.edit3_onm.setEnabled(False)
        self.edit3_onm.setGeometry(QtCore.QRect(260, 160, 31, 32))
        self.edit3_onm.setObjectName(_fromUtf8("edit3_onm"))
        self.edit3_delaym = QtGui.QLineEdit(self.centralwidget)
        self.edit3_delaym.setEnabled(False)
        self.edit3_delaym.setGeometry(QtCore.QRect(130, 160, 31, 32))
        self.edit3_delaym.setInputMask(_fromUtf8(""))
        self.edit3_delaym.setMaxLength(32767)
        self.edit3_delaym.setObjectName(_fromUtf8("edit3_delaym"))
        self.edit4_totalh = QtGui.QLineEdit(self.centralwidget)
        self.edit4_totalh.setEnabled(False)
        self.edit4_totalh.setGeometry(QtCore.QRect(490, 220, 31, 32))
        self.edit4_totalh.setObjectName(_fromUtf8("edit4_totalh"))
        self.edit4_offh = QtGui.QLineEdit(self.centralwidget)
        self.edit4_offh.setEnabled(False)
        self.edit4_offh.setGeometry(QtCore.QRect(360, 220, 31, 32))
        self.edit4_offh.setObjectName(_fromUtf8("edit4_offh"))
        self.edit4_totalm = QtGui.QLineEdit(self.centralwidget)
        self.edit4_totalm.setEnabled(False)
        self.edit4_totalm.setGeometry(QtCore.QRect(520, 220, 31, 32))
        self.edit4_totalm.setObjectName(_fromUtf8("edit4_totalm"))
        self.edit4_onh = QtGui.QLineEdit(self.centralwidget)
        self.edit4_onh.setEnabled(False)
        self.edit4_onh.setGeometry(QtCore.QRect(230, 220, 31, 32))
        self.edit4_onh.setObjectName(_fromUtf8("edit4_onh"))
        self.edit4_delayh = QtGui.QLineEdit(self.centralwidget)
        self.edit4_delayh.setEnabled(False)
        self.edit4_delayh.setGeometry(QtCore.QRect(100, 220, 31, 32))
        self.edit4_delayh.setInputMask(_fromUtf8(""))
        self.edit4_delayh.setMaxLength(32767)
        self.edit4_delayh.setObjectName(_fromUtf8("edit4_delayh"))
        self.edit4_offm = QtGui.QLineEdit(self.centralwidget)
        self.edit4_offm.setEnabled(False)
        self.edit4_offm.setGeometry(QtCore.QRect(390, 220, 31, 32))
        self.edit4_offm.setObjectName(_fromUtf8("edit4_offm"))
        self.edit4_onm = QtGui.QLineEdit(self.centralwidget)
        self.edit4_onm.setEnabled(False)
        self.edit4_onm.setGeometry(QtCore.QRect(260, 220, 31, 32))
        self.edit4_onm.setObjectName(_fromUtf8("edit4_onm"))
        self.edit4_delaym = QtGui.QLineEdit(self.centralwidget)
        self.edit4_delaym.setEnabled(False)
        self.edit4_delaym.setGeometry(QtCore.QRect(130, 220, 31, 32))
        self.edit4_delaym.setInputMask(_fromUtf8(""))
        self.edit4_delaym.setMaxLength(32767)
        self.edit4_delaym.setObjectName(_fromUtf8("edit4_delaym"))
        self.edit5_totalh = QtGui.QLineEdit(self.centralwidget)
        self.edit5_totalh.setEnabled(False)
        self.edit5_totalh.setGeometry(QtCore.QRect(490, 280, 31, 32))
        self.edit5_totalh.setObjectName(_fromUtf8("edit5_totalh"))
        self.edit5_offh = QtGui.QLineEdit(self.centralwidget)
        self.edit5_offh.setEnabled(False)
        self.edit5_offh.setGeometry(QtCore.QRect(360, 280, 31, 32))
        self.edit5_offh.setObjectName(_fromUtf8("edit5_offh"))
        self.edit5_totalm = QtGui.QLineEdit(self.centralwidget)
        self.edit5_totalm.setEnabled(False)
        self.edit5_totalm.setGeometry(QtCore.QRect(520, 280, 31, 32))
        self.edit5_totalm.setObjectName(_fromUtf8("edit5_totalm"))
        self.edit5_onh = QtGui.QLineEdit(self.centralwidget)
        self.edit5_onh.setEnabled(False)
        self.edit5_onh.setGeometry(QtCore.QRect(230, 280, 31, 32))
        self.edit5_onh.setObjectName(_fromUtf8("edit5_onh"))
        self.edit5_delayh = QtGui.QLineEdit(self.centralwidget)
        self.edit5_delayh.setEnabled(False)
        self.edit5_delayh.setGeometry(QtCore.QRect(100, 280, 31, 32))
        self.edit5_delayh.setInputMask(_fromUtf8(""))
        self.edit5_delayh.setMaxLength(32767)
        self.edit5_delayh.setObjectName(_fromUtf8("edit5_delayh"))
        self.edit5_offm = QtGui.QLineEdit(self.centralwidget)
        self.edit5_offm.setEnabled(False)
        self.edit5_offm.setGeometry(QtCore.QRect(390, 280, 31, 32))
        self.edit5_offm.setObjectName(_fromUtf8("edit5_offm"))
        self.edit5_onm = QtGui.QLineEdit(self.centralwidget)
        self.edit5_onm.setEnabled(False)
        self.edit5_onm.setGeometry(QtCore.QRect(260, 280, 31, 32))
        self.edit5_onm.setObjectName(_fromUtf8("edit5_onm"))
        self.edit5_delaym = QtGui.QLineEdit(self.centralwidget)
        self.edit5_delaym.setEnabled(False)
        self.edit5_delaym.setGeometry(QtCore.QRect(130, 280, 31, 32))
        self.edit5_delaym.setInputMask(_fromUtf8(""))
        self.edit5_delaym.setMaxLength(32767)
        self.edit5_delaym.setObjectName(_fromUtf8("edit5_delaym"))
        self.edit6_totalh = QtGui.QLineEdit(self.centralwidget)
        self.edit6_totalh.setEnabled(False)
        self.edit6_totalh.setGeometry(QtCore.QRect(490, 340, 31, 32))
        self.edit6_totalh.setObjectName(_fromUtf8("edit6_totalh"))
        self.edit6_offh = QtGui.QLineEdit(self.centralwidget)
        self.edit6_offh.setEnabled(False)
        self.edit6_offh.setGeometry(QtCore.QRect(360, 340, 31, 32))
        self.edit6_offh.setObjectName(_fromUtf8("edit6_offh"))
        self.edit6_totalm = QtGui.QLineEdit(self.centralwidget)
        self.edit6_totalm.setEnabled(False)
        self.edit6_totalm.setGeometry(QtCore.QRect(520, 340, 31, 32))
        self.edit6_totalm.setObjectName(_fromUtf8("edit6_totalm"))
        self.edit6_onh = QtGui.QLineEdit(self.centralwidget)
        self.edit6_onh.setEnabled(False)
        self.edit6_onh.setGeometry(QtCore.QRect(230, 340, 31, 32))
        self.edit6_onh.setObjectName(_fromUtf8("edit6_onh"))
        self.edit6_delayh = QtGui.QLineEdit(self.centralwidget)
        self.edit6_delayh.setEnabled(False)
        self.edit6_delayh.setGeometry(QtCore.QRect(100, 340, 31, 32))
        self.edit6_delayh.setInputMask(_fromUtf8(""))
        self.edit6_delayh.setMaxLength(32767)
        self.edit6_delayh.setObjectName(_fromUtf8("edit6_delayh"))
        self.edit6_offm = QtGui.QLineEdit(self.centralwidget)
        self.edit6_offm.setEnabled(False)
        self.edit6_offm.setGeometry(QtCore.QRect(390, 340, 31, 32))
        self.edit6_offm.setObjectName(_fromUtf8("edit6_offm"))
        self.edit6_onm = QtGui.QLineEdit(self.centralwidget)
        self.edit6_onm.setEnabled(False)
        self.edit6_onm.setGeometry(QtCore.QRect(260, 340, 31, 32))
        self.edit6_onm.setObjectName(_fromUtf8("edit6_onm"))
        self.edit6_delaym = QtGui.QLineEdit(self.centralwidget)
        self.edit6_delaym.setEnabled(False)
        self.edit6_delaym.setGeometry(QtCore.QRect(130, 340, 31, 32))
        self.edit6_delaym.setInputMask(_fromUtf8(""))
        self.edit6_delaym.setMaxLength(32767)
        self.edit6_delaym.setObjectName(_fromUtf8("edit6_delaym"))
        self.edit7_totalh = QtGui.QLineEdit(self.centralwidget)
        self.edit7_totalh.setEnabled(False)
        self.edit7_totalh.setGeometry(QtCore.QRect(490, 400, 31, 32))
        self.edit7_totalh.setObjectName(_fromUtf8("edit7_totalh"))
        self.edit7_offh = QtGui.QLineEdit(self.centralwidget)
        self.edit7_offh.setEnabled(False)
        self.edit7_offh.setGeometry(QtCore.QRect(360, 400, 31, 32))
        self.edit7_offh.setObjectName(_fromUtf8("edit7_offh"))
        self.edit7_totalm = QtGui.QLineEdit(self.centralwidget)
        self.edit7_totalm.setEnabled(False)
        self.edit7_totalm.setGeometry(QtCore.QRect(520, 400, 31, 32))
        self.edit7_totalm.setObjectName(_fromUtf8("edit7_totalm"))
        self.edit7_onh = QtGui.QLineEdit(self.centralwidget)
        self.edit7_onh.setEnabled(False)
        self.edit7_onh.setGeometry(QtCore.QRect(230, 400, 31, 32))
        self.edit7_onh.setObjectName(_fromUtf8("edit7_onh"))
        self.edit7_delayh = QtGui.QLineEdit(self.centralwidget)
        self.edit7_delayh.setEnabled(False)
        self.edit7_delayh.setGeometry(QtCore.QRect(100, 400, 31, 32))
        self.edit7_delayh.setInputMask(_fromUtf8(""))
        self.edit7_delayh.setMaxLength(32767)
        self.edit7_delayh.setObjectName(_fromUtf8("edit7_delayh"))
        self.edit7_offm = QtGui.QLineEdit(self.centralwidget)
        self.edit7_offm.setEnabled(False)
        self.edit7_offm.setGeometry(QtCore.QRect(390, 400, 31, 32))
        self.edit7_offm.setObjectName(_fromUtf8("edit7_offm"))
        self.edit7_onm = QtGui.QLineEdit(self.centralwidget)
        self.edit7_onm.setEnabled(False)
        self.edit7_onm.setGeometry(QtCore.QRect(260, 400, 31, 32))
        self.edit7_onm.setObjectName(_fromUtf8("edit7_onm"))
        self.edit7_delaym = QtGui.QLineEdit(self.centralwidget)
        self.edit7_delaym.setEnabled(False)
        self.edit7_delaym.setGeometry(QtCore.QRect(130, 400, 31, 32))
        self.edit7_delaym.setInputMask(_fromUtf8(""))
        self.edit7_delaym.setMaxLength(32767)
        self.edit7_delaym.setObjectName(_fromUtf8("edit7_delaym"))
        self.edit8_totalh = QtGui.QLineEdit(self.centralwidget)
        self.edit8_totalh.setEnabled(False)
        self.edit8_totalh.setGeometry(QtCore.QRect(490, 460, 31, 32))
        self.edit8_totalh.setObjectName(_fromUtf8("edit8_totalh"))
        self.edit8_offh = QtGui.QLineEdit(self.centralwidget)
        self.edit8_offh.setEnabled(False)
        self.edit8_offh.setGeometry(QtCore.QRect(360, 460, 31, 32))
        self.edit8_offh.setObjectName(_fromUtf8("edit8_offh"))
        self.edit8_totalm = QtGui.QLineEdit(self.centralwidget)
        self.edit8_totalm.setEnabled(False)
        self.edit8_totalm.setGeometry(QtCore.QRect(520, 460, 31, 32))
        self.edit8_totalm.setObjectName(_fromUtf8("edit8_totalm"))
        self.edit8_onh = QtGui.QLineEdit(self.centralwidget)
        self.edit8_onh.setEnabled(False)
        self.edit8_onh.setGeometry(QtCore.QRect(230, 460, 31, 32))
        self.edit8_onh.setObjectName(_fromUtf8("edit8_onh"))
        self.edit8_delayh = QtGui.QLineEdit(self.centralwidget)
        self.edit8_delayh.setEnabled(False)
        self.edit8_delayh.setGeometry(QtCore.QRect(100, 460, 31, 32))
        self.edit8_delayh.setInputMask(_fromUtf8(""))
        self.edit8_delayh.setMaxLength(32767)
        self.edit8_delayh.setObjectName(_fromUtf8("edit8_delayh"))
        self.edit8_offm = QtGui.QLineEdit(self.centralwidget)
        self.edit8_offm.setEnabled(False)
        self.edit8_offm.setGeometry(QtCore.QRect(390, 460, 31, 32))
        self.edit8_offm.setObjectName(_fromUtf8("edit8_offm"))
        self.edit8_onm = QtGui.QLineEdit(self.centralwidget)
        self.edit8_onm.setEnabled(False)
        self.edit8_onm.setGeometry(QtCore.QRect(260, 460, 31, 32))
        self.edit8_onm.setObjectName(_fromUtf8("edit8_onm"))
        self.edit8_delaym = QtGui.QLineEdit(self.centralwidget)
        self.edit8_delaym.setEnabled(False)
        self.edit8_delaym.setGeometry(QtCore.QRect(130, 460, 31, 32))
        self.edit8_delaym.setInputMask(_fromUtf8(""))
        self.edit8_delaym.setMaxLength(32767)
        self.edit8_delaym.setObjectName(_fromUtf8("edit8_delaym"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 64, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.btn_execute = QtGui.QPushButton(self.centralwidget)
        self.btn_execute.setGeometry(QtCore.QRect(110, 520, 96, 32))
        self.btn_execute.setObjectName(_fromUtf8("btn_execute"))
        self.btn_save = QtGui.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(240, 520, 96, 32))
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.btn_open = QtGui.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(370, 520, 96, 32))
        self.btn_open.setObjectName(_fromUtf8("btn_open"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(200, 10, 20, 491))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(330, 10, 20, 491))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(460, 10, 20, 491))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(70, 10, 20, 491))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.edit1_delays = QtGui.QLineEdit(self.centralwidget)
        self.edit1_delays.setEnabled(False)
        self.edit1_delays.setGeometry(QtCore.QRect(160, 40, 31, 32))
        self.edit1_delays.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit1_delays.setInputMask(_fromUtf8(""))
        self.edit1_delays.setMaxLength(32767)
        self.edit1_delays.setObjectName(_fromUtf8("edit1_delays"))
        self.edit2_delays = QtGui.QLineEdit(self.centralwidget)
        self.edit2_delays.setEnabled(False)
        self.edit2_delays.setGeometry(QtCore.QRect(160, 100, 31, 32))
        self.edit2_delays.setInputMask(_fromUtf8(""))
        self.edit2_delays.setMaxLength(32767)
        self.edit2_delays.setObjectName(_fromUtf8("edit2_delays"))
        self.edit3_delays = QtGui.QLineEdit(self.centralwidget)
        self.edit3_delays.setEnabled(False)
        self.edit3_delays.setGeometry(QtCore.QRect(160, 160, 31, 32))
        self.edit3_delays.setInputMask(_fromUtf8(""))
        self.edit3_delays.setMaxLength(32767)
        self.edit3_delays.setObjectName(_fromUtf8("edit3_delays"))
        self.edit4_delays = QtGui.QLineEdit(self.centralwidget)
        self.edit4_delays.setEnabled(False)
        self.edit4_delays.setGeometry(QtCore.QRect(160, 220, 31, 32))
        self.edit4_delays.setInputMask(_fromUtf8(""))
        self.edit4_delays.setMaxLength(32767)
        self.edit4_delays.setObjectName(_fromUtf8("edit4_delays"))
        self.edit5_delays = QtGui.QLineEdit(self.centralwidget)
        self.edit5_delays.setEnabled(False)
        self.edit5_delays.setGeometry(QtCore.QRect(160, 280, 31, 32))
        self.edit5_delays.setInputMask(_fromUtf8(""))
        self.edit5_delays.setMaxLength(32767)
        self.edit5_delays.setObjectName(_fromUtf8("edit5_delays"))
        self.edit6_delays = QtGui.QLineEdit(self.centralwidget)
        self.edit6_delays.setEnabled(False)
        self.edit6_delays.setGeometry(QtCore.QRect(160, 340, 31, 32))
        self.edit6_delays.setInputMask(_fromUtf8(""))
        self.edit6_delays.setMaxLength(32767)
        self.edit6_delays.setObjectName(_fromUtf8("edit6_delays"))
        self.edit7_delays = QtGui.QLineEdit(self.centralwidget)
        self.edit7_delays.setEnabled(False)
        self.edit7_delays.setGeometry(QtCore.QRect(160, 400, 31, 32))
        self.edit7_delays.setInputMask(_fromUtf8(""))
        self.edit7_delays.setMaxLength(32767)
        self.edit7_delays.setObjectName(_fromUtf8("edit7_delays"))
        self.edit8_delays = QtGui.QLineEdit(self.centralwidget)
        self.edit8_delays.setEnabled(False)
        self.edit8_delays.setGeometry(QtCore.QRect(160, 460, 31, 32))
        self.edit8_delays.setInputMask(_fromUtf8(""))
        self.edit8_delays.setMaxLength(32767)
        self.edit8_delays.setObjectName(_fromUtf8("edit8_delays"))
        self.edit1_ons = QtGui.QLineEdit(self.centralwidget)
        self.edit1_ons.setEnabled(False)
        self.edit1_ons.setGeometry(QtCore.QRect(290, 40, 31, 32))
        self.edit1_ons.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit1_ons.setObjectName(_fromUtf8("edit1_ons"))
        self.edit2_ons = QtGui.QLineEdit(self.centralwidget)
        self.edit2_ons.setEnabled(False)
        self.edit2_ons.setGeometry(QtCore.QRect(290, 100, 31, 32))
        self.edit2_ons.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit2_ons.setObjectName(_fromUtf8("edit2_ons"))
        self.edit3_ons = QtGui.QLineEdit(self.centralwidget)
        self.edit3_ons.setEnabled(False)
        self.edit3_ons.setGeometry(QtCore.QRect(290, 160, 31, 32))
        self.edit3_ons.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit3_ons.setObjectName(_fromUtf8("edit3_ons"))
        self.edit4_ons = QtGui.QLineEdit(self.centralwidget)
        self.edit4_ons.setEnabled(False)
        self.edit4_ons.setGeometry(QtCore.QRect(290, 220, 31, 32))
        self.edit4_ons.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit4_ons.setObjectName(_fromUtf8("edit4_ons"))
        self.edit5_ons = QtGui.QLineEdit(self.centralwidget)
        self.edit5_ons.setEnabled(False)
        self.edit5_ons.setGeometry(QtCore.QRect(290, 280, 31, 32))
        self.edit5_ons.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit5_ons.setObjectName(_fromUtf8("edit5_ons"))
        self.edit6_ons = QtGui.QLineEdit(self.centralwidget)
        self.edit6_ons.setEnabled(False)
        self.edit6_ons.setGeometry(QtCore.QRect(290, 340, 31, 32))
        self.edit6_ons.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit6_ons.setObjectName(_fromUtf8("edit6_ons"))
        self.edit7_ons = QtGui.QLineEdit(self.centralwidget)
        self.edit7_ons.setEnabled(False)
        self.edit7_ons.setGeometry(QtCore.QRect(290, 400, 31, 32))
        self.edit7_ons.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit7_ons.setObjectName(_fromUtf8("edit7_ons"))
        self.edit8_ons = QtGui.QLineEdit(self.centralwidget)
        self.edit8_ons.setEnabled(False)
        self.edit8_ons.setGeometry(QtCore.QRect(290, 460, 31, 32))
        self.edit8_ons.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit8_ons.setObjectName(_fromUtf8("edit8_ons"))
        self.edit1_offs = QtGui.QLineEdit(self.centralwidget)
        self.edit1_offs.setEnabled(False)
        self.edit1_offs.setGeometry(QtCore.QRect(420, 40, 31, 32))
        self.edit1_offs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit1_offs.setObjectName(_fromUtf8("edit1_offs"))
        self.edit2_offs = QtGui.QLineEdit(self.centralwidget)
        self.edit2_offs.setEnabled(False)
        self.edit2_offs.setGeometry(QtCore.QRect(420, 100, 31, 32))
        self.edit2_offs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit2_offs.setObjectName(_fromUtf8("edit2_offs"))
        self.edit3_offs = QtGui.QLineEdit(self.centralwidget)
        self.edit3_offs.setEnabled(False)
        self.edit3_offs.setGeometry(QtCore.QRect(420, 160, 31, 32))
        self.edit3_offs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit3_offs.setObjectName(_fromUtf8("edit3_offs"))
        self.edit4_offs = QtGui.QLineEdit(self.centralwidget)
        self.edit4_offs.setEnabled(False)
        self.edit4_offs.setGeometry(QtCore.QRect(420, 220, 31, 32))
        self.edit4_offs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit4_offs.setObjectName(_fromUtf8("edit4_offs"))
        self.edit5_offs = QtGui.QLineEdit(self.centralwidget)
        self.edit5_offs.setEnabled(False)
        self.edit5_offs.setGeometry(QtCore.QRect(420, 280, 31, 32))
        self.edit5_offs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit5_offs.setObjectName(_fromUtf8("edit5_offs"))
        self.edit6_offs = QtGui.QLineEdit(self.centralwidget)
        self.edit6_offs.setEnabled(False)
        self.edit6_offs.setGeometry(QtCore.QRect(420, 340, 31, 32))
        self.edit6_offs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit6_offs.setObjectName(_fromUtf8("edit6_offs"))
        self.edit7_offs = QtGui.QLineEdit(self.centralwidget)
        self.edit7_offs.setEnabled(False)
        self.edit7_offs.setGeometry(QtCore.QRect(420, 400, 31, 32))
        self.edit7_offs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit7_offs.setObjectName(_fromUtf8("edit7_offs"))
        self.edit8_offs = QtGui.QLineEdit(self.centralwidget)
        self.edit8_offs.setEnabled(False)
        self.edit8_offs.setGeometry(QtCore.QRect(420, 460, 31, 32))
        self.edit8_offs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit8_offs.setObjectName(_fromUtf8("edit8_offs"))
        self.edit1_totals = QtGui.QLineEdit(self.centralwidget)
        self.edit1_totals.setEnabled(False)
        self.edit1_totals.setGeometry(QtCore.QRect(550, 40, 31, 32))
        self.edit1_totals.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit1_totals.setObjectName(_fromUtf8("edit1_totals"))
        self.edit2_totals = QtGui.QLineEdit(self.centralwidget)
        self.edit2_totals.setEnabled(False)
        self.edit2_totals.setGeometry(QtCore.QRect(550, 100, 31, 32))
        self.edit2_totals.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit2_totals.setObjectName(_fromUtf8("edit2_totals"))
        self.edit3_totals = QtGui.QLineEdit(self.centralwidget)
        self.edit3_totals.setEnabled(False)
        self.edit3_totals.setGeometry(QtCore.QRect(550, 160, 31, 32))
        self.edit3_totals.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit3_totals.setObjectName(_fromUtf8("edit3_totals"))
        self.edit4_totals = QtGui.QLineEdit(self.centralwidget)
        self.edit4_totals.setEnabled(False)
        self.edit4_totals.setGeometry(QtCore.QRect(550, 220, 31, 32))
        self.edit4_totals.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit4_totals.setObjectName(_fromUtf8("edit4_totals"))
        self.edit5_totals = QtGui.QLineEdit(self.centralwidget)
        self.edit5_totals.setEnabled(False)
        self.edit5_totals.setGeometry(QtCore.QRect(550, 280, 31, 32))
        self.edit5_totals.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit5_totals.setObjectName(_fromUtf8("edit5_totals"))
        self.edit6_totals = QtGui.QLineEdit(self.centralwidget)
        self.edit6_totals.setEnabled(False)
        self.edit6_totals.setGeometry(QtCore.QRect(550, 340, 31, 32))
        self.edit6_totals.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit6_totals.setObjectName(_fromUtf8("edit6_totals"))
        self.edit7_totals = QtGui.QLineEdit(self.centralwidget)
        self.edit7_totals.setEnabled(False)
        self.edit7_totals.setGeometry(QtCore.QRect(550, 400, 31, 32))
        self.edit7_totals.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit7_totals.setObjectName(_fromUtf8("edit7_totals"))
        self.edit8_totals = QtGui.QLineEdit(self.centralwidget)
        self.edit8_totals.setEnabled(False)
        self.edit8_totals.setGeometry(QtCore.QRect(550, 460, 31, 32))
        self.edit8_totals.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit8_totals.setObjectName(_fromUtf8("edit8_totals"))
        ValvulasMainWindow.setCentralWidget(self.centralwidget)
        self.statusBar1 = QtGui.QStatusBar(ValvulasMainWindow)
        self.statusBar1.setObjectName(_fromUtf8("statusBar1"))
        ValvulasMainWindow.setStatusBar(self.statusBar1)
        self.toolBar1 = QtGui.QToolBar(ValvulasMainWindow)
        self.toolBar1.setMovable(False)
        self.toolBar1.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar1.setFloatable(False)
        self.toolBar1.setObjectName(_fromUtf8("toolBar1"))
        ValvulasMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar1)

        self.retranslateUi(ValvulasMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ValvulasMainWindow)
        ValvulasMainWindow.setTabOrder(self.valve1, self.edit1_delayh)
        ValvulasMainWindow.setTabOrder(self.edit1_delayh, self.edit1_delaym)
        ValvulasMainWindow.setTabOrder(self.edit1_delaym, self.edit1_delays)
        ValvulasMainWindow.setTabOrder(self.edit1_delays, self.edit1_onh)
        ValvulasMainWindow.setTabOrder(self.edit1_onh, self.edit1_onm)
        ValvulasMainWindow.setTabOrder(self.edit1_onm, self.edit1_ons)
        ValvulasMainWindow.setTabOrder(self.edit1_ons, self.edit1_offh)
        ValvulasMainWindow.setTabOrder(self.edit1_offh, self.edit1_offm)
        ValvulasMainWindow.setTabOrder(self.edit1_offm, self.edit1_offs)
        ValvulasMainWindow.setTabOrder(self.edit1_offs, self.edit1_totalh)
        ValvulasMainWindow.setTabOrder(self.edit1_totalh, self.edit1_totalm)
        ValvulasMainWindow.setTabOrder(self.edit1_totalm, self.edit1_totals)
        ValvulasMainWindow.setTabOrder(self.edit1_totals, self.valve2)
        ValvulasMainWindow.setTabOrder(self.valve2, self.edit2_delayh)
        ValvulasMainWindow.setTabOrder(self.edit2_delayh, self.edit2_delaym)
        ValvulasMainWindow.setTabOrder(self.edit2_delaym, self.edit2_delays)
        ValvulasMainWindow.setTabOrder(self.edit2_delays, self.edit2_onh)
        ValvulasMainWindow.setTabOrder(self.edit2_onh, self.edit2_onm)
        ValvulasMainWindow.setTabOrder(self.edit2_onm, self.edit2_ons)
        ValvulasMainWindow.setTabOrder(self.edit2_ons, self.edit2_offh)
        ValvulasMainWindow.setTabOrder(self.edit2_offh, self.edit2_offm)
        ValvulasMainWindow.setTabOrder(self.edit2_offm, self.edit2_offs)
        ValvulasMainWindow.setTabOrder(self.edit2_offs, self.edit2_totalh)
        ValvulasMainWindow.setTabOrder(self.edit2_totalh, self.edit2_totalm)
        ValvulasMainWindow.setTabOrder(self.edit2_totalm, self.edit2_totals)
        ValvulasMainWindow.setTabOrder(self.edit2_totals, self.valve3)
        ValvulasMainWindow.setTabOrder(self.valve3, self.edit3_delayh)
        ValvulasMainWindow.setTabOrder(self.edit3_delayh, self.edit3_delaym)
        ValvulasMainWindow.setTabOrder(self.edit3_delaym, self.edit3_delays)
        ValvulasMainWindow.setTabOrder(self.edit3_delays, self.edit3_onh)
        ValvulasMainWindow.setTabOrder(self.edit3_onh, self.edit3_onm)
        ValvulasMainWindow.setTabOrder(self.edit3_onm, self.edit3_ons)
        ValvulasMainWindow.setTabOrder(self.edit3_ons, self.edit3_offh)
        ValvulasMainWindow.setTabOrder(self.edit3_offh, self.edit3_offm)
        ValvulasMainWindow.setTabOrder(self.edit3_offm, self.edit3_offs)
        ValvulasMainWindow.setTabOrder(self.edit3_offs, self.edit3_totalh)
        ValvulasMainWindow.setTabOrder(self.edit3_totalh, self.edit3_totalm)
        ValvulasMainWindow.setTabOrder(self.edit3_totalm, self.edit3_totals)
        ValvulasMainWindow.setTabOrder(self.edit3_totals, self.valve4)
        ValvulasMainWindow.setTabOrder(self.valve4, self.edit4_delayh)
        ValvulasMainWindow.setTabOrder(self.edit4_delayh, self.edit4_delaym)
        ValvulasMainWindow.setTabOrder(self.edit4_delaym, self.edit4_delays)
        ValvulasMainWindow.setTabOrder(self.edit4_delays, self.edit4_onh)
        ValvulasMainWindow.setTabOrder(self.edit4_onh, self.edit4_onm)
        ValvulasMainWindow.setTabOrder(self.edit4_onm, self.edit4_ons)
        ValvulasMainWindow.setTabOrder(self.edit4_ons, self.edit4_offh)
        ValvulasMainWindow.setTabOrder(self.edit4_offh, self.edit4_offm)
        ValvulasMainWindow.setTabOrder(self.edit4_offm, self.edit4_offs)
        ValvulasMainWindow.setTabOrder(self.edit4_offs, self.edit4_totalh)
        ValvulasMainWindow.setTabOrder(self.edit4_totalh, self.edit4_totalm)
        ValvulasMainWindow.setTabOrder(self.edit4_totalm, self.edit4_totals)
        ValvulasMainWindow.setTabOrder(self.edit4_totals, self.valve5)
        ValvulasMainWindow.setTabOrder(self.valve5, self.edit5_delayh)
        ValvulasMainWindow.setTabOrder(self.edit5_delayh, self.edit5_delaym)
        ValvulasMainWindow.setTabOrder(self.edit5_delaym, self.edit5_delays)
        ValvulasMainWindow.setTabOrder(self.edit5_delays, self.edit5_onh)
        ValvulasMainWindow.setTabOrder(self.edit5_onh, self.edit5_onm)
        ValvulasMainWindow.setTabOrder(self.edit5_onm, self.edit5_ons)
        ValvulasMainWindow.setTabOrder(self.edit5_ons, self.edit5_offh)
        ValvulasMainWindow.setTabOrder(self.edit5_offh, self.edit5_offm)
        ValvulasMainWindow.setTabOrder(self.edit5_offm, self.edit5_offs)
        ValvulasMainWindow.setTabOrder(self.edit5_offs, self.edit5_totalh)
        ValvulasMainWindow.setTabOrder(self.edit5_totalh, self.edit5_totalm)
        ValvulasMainWindow.setTabOrder(self.edit5_totalm, self.edit5_totals)
        ValvulasMainWindow.setTabOrder(self.edit5_totals, self.valve6)
        ValvulasMainWindow.setTabOrder(self.valve6, self.edit6_delayh)
        ValvulasMainWindow.setTabOrder(self.edit6_delayh, self.edit6_delaym)
        ValvulasMainWindow.setTabOrder(self.edit6_delaym, self.edit6_delays)
        ValvulasMainWindow.setTabOrder(self.edit6_delays, self.edit6_onh)
        ValvulasMainWindow.setTabOrder(self.edit6_onh, self.edit6_onm)
        ValvulasMainWindow.setTabOrder(self.edit6_onm, self.edit6_ons)
        ValvulasMainWindow.setTabOrder(self.edit6_ons, self.edit6_offh)
        ValvulasMainWindow.setTabOrder(self.edit6_offh, self.edit6_offm)
        ValvulasMainWindow.setTabOrder(self.edit6_offm, self.edit6_offs)
        ValvulasMainWindow.setTabOrder(self.edit6_offs, self.edit6_totalh)
        ValvulasMainWindow.setTabOrder(self.edit6_totalh, self.edit6_totalm)
        ValvulasMainWindow.setTabOrder(self.edit6_totalm, self.edit6_totals)
        ValvulasMainWindow.setTabOrder(self.edit6_totals, self.valve7)
        ValvulasMainWindow.setTabOrder(self.valve7, self.edit7_delayh)
        ValvulasMainWindow.setTabOrder(self.edit7_delayh, self.edit7_delaym)
        ValvulasMainWindow.setTabOrder(self.edit7_delaym, self.edit7_delays)
        ValvulasMainWindow.setTabOrder(self.edit7_delays, self.edit7_onh)
        ValvulasMainWindow.setTabOrder(self.edit7_onh, self.edit7_onm)
        ValvulasMainWindow.setTabOrder(self.edit7_onm, self.edit7_ons)
        ValvulasMainWindow.setTabOrder(self.edit7_ons, self.edit7_offh)
        ValvulasMainWindow.setTabOrder(self.edit7_offh, self.edit7_offm)
        ValvulasMainWindow.setTabOrder(self.edit7_offm, self.edit7_offs)
        ValvulasMainWindow.setTabOrder(self.edit7_offs, self.edit7_totalh)
        ValvulasMainWindow.setTabOrder(self.edit7_totalh, self.edit7_totalm)
        ValvulasMainWindow.setTabOrder(self.edit7_totalm, self.edit7_totals)
        ValvulasMainWindow.setTabOrder(self.edit7_totals, self.valve8)
        ValvulasMainWindow.setTabOrder(self.valve8, self.edit8_delayh)
        ValvulasMainWindow.setTabOrder(self.edit8_delayh, self.edit8_delaym)
        ValvulasMainWindow.setTabOrder(self.edit8_delaym, self.edit8_delays)
        ValvulasMainWindow.setTabOrder(self.edit8_delays, self.edit8_onh)
        ValvulasMainWindow.setTabOrder(self.edit8_onh, self.edit8_onm)
        ValvulasMainWindow.setTabOrder(self.edit8_onm, self.edit8_ons)
        ValvulasMainWindow.setTabOrder(self.edit8_ons, self.edit8_offh)
        ValvulasMainWindow.setTabOrder(self.edit8_offh, self.edit8_offm)
        ValvulasMainWindow.setTabOrder(self.edit8_offm, self.edit8_offs)
        ValvulasMainWindow.setTabOrder(self.edit8_offs, self.edit8_totalh)
        ValvulasMainWindow.setTabOrder(self.edit8_totalh, self.edit8_totalm)
        ValvulasMainWindow.setTabOrder(self.edit8_totalm, self.edit8_totals)
        ValvulasMainWindow.setTabOrder(self.edit8_totals, self.btn_execute)
        ValvulasMainWindow.setTabOrder(self.btn_execute, self.btn_save)
        ValvulasMainWindow.setTabOrder(self.btn_save, self.btn_open)

    def retranslateUi(self, ValvulasMainWindow):
        ValvulasMainWindow.setWindowTitle(_translate("ValvulasMainWindow", "ValvulasMainWindow", None))
        self.valve1.setText(_translate("ValvulasMainWindow", "1", None))
        self.valve2.setText(_translate("ValvulasMainWindow", "2", None))
        self.valve3.setText(_translate("ValvulasMainWindow", "3", None))
        self.valve4.setText(_translate("ValvulasMainWindow", "4", None))
        self.valve5.setText(_translate("ValvulasMainWindow", "5", None))
        self.valve6.setText(_translate("ValvulasMainWindow", "6", None))
        self.valve7.setText(_translate("ValvulasMainWindow", "7", None))
        self.valve8.setText(_translate("ValvulasMainWindow", "8", None))
        self.label.setText(_translate("ValvulasMainWindow", "Delay", None))
        self.label_2.setText(_translate("ValvulasMainWindow", "On", None))
        self.label_3.setText(_translate("ValvulasMainWindow", "Off", None))
        self.label_4.setText(_translate("ValvulasMainWindow", "Total", None))
        self.edit1_delayh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit1_delaym.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit1_onh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit1_onm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit1_offh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit1_offm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit1_totalh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit1_totalm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit2_onh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit2_offh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit2_totalh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit2_onm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit2_totalm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit2_delayh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit2_delaym.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit2_offm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit3_onh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit3_totalm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit3_totalh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit3_delayh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit3_offm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit3_offh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit3_onm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit3_delaym.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit4_totalh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit4_offh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit4_totalm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit4_onh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit4_delayh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit4_offm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit4_onm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit4_delaym.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit5_totalh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit5_offh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit5_totalm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit5_onh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit5_delayh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit5_offm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit5_onm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit5_delaym.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit6_totalh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit6_offh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit6_totalm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit6_onh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit6_delayh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit6_offm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit6_onm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit6_delaym.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit7_totalh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit7_offh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit7_totalm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit7_onh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit7_delayh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit7_offm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit7_onm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit7_delaym.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit8_totalh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit8_offh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit8_totalm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit8_onh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit8_delayh.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit8_offm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit8_onm.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit8_delaym.setText(_translate("ValvulasMainWindow", "0", None))
        self.label_5.setText(_translate("ValvulasMainWindow", "Valvula", None))
        self.btn_execute.setText(_translate("ValvulasMainWindow", "&Ejecutar", None))
        self.btn_save.setText(_translate("ValvulasMainWindow", "Guardar", None))
        self.btn_open.setText(_translate("ValvulasMainWindow", "&Open", None))
        self.edit1_delays.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit2_delays.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit3_delays.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit4_delays.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit5_delays.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit6_delays.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit7_delays.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit8_delays.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit1_ons.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit2_ons.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit3_ons.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit4_ons.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit5_ons.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit6_ons.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit7_ons.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit8_ons.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit1_offs.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit2_offs.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit3_offs.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit4_offs.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit5_offs.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit6_offs.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit7_offs.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit8_offs.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit1_totals.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit2_totals.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit3_totals.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit4_totals.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit5_totals.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit6_totals.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit7_totals.setText(_translate("ValvulasMainWindow", "0", None))
        self.edit8_totals.setText(_translate("ValvulasMainWindow", "0", None))
        self.toolBar1.setWindowTitle(_translate("ValvulasMainWindow", "toolBar", None))

